#!/usr/bin/env node
// Inlines the curated data/*-{db,en}.json into a single generated TS module so
// the library is portable (no Vite import.meta.glob, no JSON-in-dist concerns).
//
//   node generate.mjs   ->  ../src/generated.ts
//
// Re-run after apply.mjs changes the data files.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA = path.resolve(__dirname, '../data');
const OUT = path.resolve(__dirname, '../src/generated.ts');

const codes = [
  ...new Set(
    fs
      .readdirSync(DATA)
      .filter((f) => f.endsWith('-db.json'))
      .map((f) => f.replace('-db.json', ''))
  ),
].sort();

const db = {};
const en = {};
for (const code of codes) {
  db[code] = JSON.parse(fs.readFileSync(path.join(DATA, `${code}-db.json`), 'utf8'));
  en[code] = JSON.parse(fs.readFileSync(path.join(DATA, `${code}-en.json`), 'utf8'));
}

const out = `// AUTO-GENERATED by tools/generate.mjs — do not edit by hand.
// Source of truth: the curated data/*-{db,en}.json files (built by the
// curation -> apply.mjs pipeline). Re-run \`node tools/generate.mjs\` to refresh.
/* eslint-disable */
import type { CampaignLogDb, CampaignLogEn } from './types.js';

export const DB: Record<string, CampaignLogDb> = ${JSON.stringify(db)};

export const EN: Record<string, CampaignLogEn> = ${JSON.stringify(en)};
`;

fs.writeFileSync(OUT, out);
console.log(`wrote src/generated.ts (${codes.length} campaigns, ${(out.length / 1024).toFixed(0)} KB)`);
