/**
 * Font Awesome icon types used in the application.
 * Each enum value corresponds to a specific SVG file.
 */
export enum FaIconType {
	Customizable,
	Bonded,
	Exceptional,
	Permanent,
	Investigator,
	Weakness,
	AnyWeakness,
	Myriad,
	Specialist,
	Advanced,
	Reward,
	Researched,
	Fast,

	EncounterSubset,
	Dropdown,
	LeftSingle,
	LeftDouble,
	RightSingle,
	RightDouble,
	ArrowUp,
	ArrowUpAdd,
	ArrowDown,
	ArrowDownAdd,
	Import,
	Export,
	Add,
	Edit,
	Back,
	ArrowLeftBordered,
	ArrowRightBordered,
	Delete,
	DeleteList,
	Unlock,
	Collapse,
	InvestigatorRestriction,
	NoticeInfo,
	NoticeSuccess,
	NoticeError,
	Loading,
	Manual,
	Plus,
	Minus,
	Grip,
	SectionSeparator,
	SetupReferenceNotes,
	SetupReferenceAdditionalCards,
	SetupReferenceSetupChanges,
	SetupReferenceExplorationDeck,
	SetupReferenceSpectralDeck,
	SetupReferenceConcealedMiniCards,

	UpgradePlannerUpgradeTo,
	UpgradePlannerAdd,
	UpgradePlannerXpUnlock,
	UpgradePlannerXpLock,

	CardViewModeScans,
	CardViewModeList,
	CardViewModeIcons,
	GroupingSorting,

	CheckBox,
	CheckBoxChecked,
	Expand,
	Experience,
	FoldoutRight,
	FoldoutDown,
	Reset,
	Clear,
	CloseModal,
	ExternalLink
}
