// This file is auto-generated by script/generate-unions.ts
// Do not edit manually - run 'bun run sync-unions' to regenerate

import {
  TagTypeActionAdditional,
  TagTypeActionBold,
  TagTypeActionLose,
} from "./tags/action/index.js";
import {
  TagTypeAttach,
} from "./tags/attach/index.js";
import {
  TagTypeAuto,
} from "./tags/auto/index.js";
import {
  TagTypeBuffCannot,
  TagTypeBuffStatsReplace,
} from "./tags/buff/index.js";
import {
  TagTypeCancel,
} from "./tags/cancel/index.js";
import {
  TagTypeChaosEffect,
  TagTypeChaosReveal,
  TagTypeChaosSeal,
} from "./tags/chaos/index.js";
import {
  TagTypeClueAdditional,
  TagTypeClueDiscover,
} from "./tags/clue/index.js";
import {
  TagTypeCostAction,
  TagTypeCostDiscount,
  TagTypeCostFast,
  TagTypeCostFree,
  TagTypeCostOther,
  TagTypeCostReaction,
} from "./tags/cost/index.js";
import {
  TagTypeDamage,
} from "./tags/damage/index.js";
import {
  TagTypeDeckDiscard,
  TagTypeDeckDraw,
  TagTypeDeckMisc,
  TagTypeDeckSearch,
  TagTypeDeckShuffle,
} from "./tags/deck/index.js";
import {
  TagTypeDiscardFromPlay,
} from "./tags/discard/index.js";
import {
  TagTypeDiscardPile,
} from "./tags/discard-pile/index.js";
import {
  TagTypeDoom,
} from "./tags/doom/index.js";
import {
  TagTypeDuration,
} from "./tags/duration/index.js";
import {
  TagTypeEnemyDebuff,
  TagTypeEnemyElite,
  TagTypeEnemyEngage,
  TagTypeEnemyMitigation,
  TagTypeEnemyValue,
} from "./tags/enemy/index.js";
import {
  TagTypeGainKeyword,
  TagTypeGainResource,
} from "./tags/gain/index.js";
import {
  TagTypeHeal,
} from "./tags/heal/index.js";
import {
  TagTypeLocationConnecting,
  TagTypeLocationMove,
  TagTypeLocationProperty,
  TagTypeLocationShroud,
  TagTypeLocationYour,
} from "./tags/location/index.js";
import {
  TagTypePlayArea,
} from "./tags/play-area/index.js";
import {
  TagTypeRecursion,
} from "./tags/recursion/index.js";
import {
  TagTypeSkillTestCondition,
} from "./tags/skill-test-condition/index.js";
import {
  TagTypeSkillValue,
} from "./tags/skill-value/index.js";
import {
  TagTypeSlotAdditional,
} from "./tags/slot/index.js";
import {
  TagTypeStatsModBoostInTest,
  TagTypeStatsModBoostPassive,
  TagTypeStatsModPump,
} from "./tags/stats-mod/index.js";
import {
  TagTypeTestInitiate,
  TagTypeTestMisc,
  TagTypeTestResult,
} from "./tags/test/index.js";
import {
  TagTypeTestless,
} from "./tags/testless/index.js";
import {
  TagTypeTimingAfter,
  TagTypeTimingDuring,
  TagTypeTimingForced,
  TagTypeTimingGame,
  TagTypeTimingPhaseSequence,
  TagTypeTimingSkill,
  TagTypeTimingWhen,
} from "./tags/timing/index.js";
import {
  TagTypeTraitSupport,
} from "./tags/trait/index.js";
import {
  TagTypeUsesStarting,
  TagTypeUsesSupport,
} from "./tags/uses/index.js";

/**
 * All kind of unique tags defined.
 */
export type TagType =
  TagTypeActionAdditional
  | TagTypeActionBold
  | TagTypeActionLose
  | TagTypeAttach
  | TagTypeAuto
  | TagTypeBuffCannot
  | TagTypeBuffStatsReplace
  | TagTypeCancel
  | TagTypeChaosEffect
  | TagTypeChaosReveal
  | TagTypeChaosSeal
  | TagTypeClueAdditional
  | TagTypeClueDiscover
  | TagTypeCostAction
  | TagTypeCostDiscount
  | TagTypeCostFast
  | TagTypeCostFree
  | TagTypeCostOther
  | TagTypeCostReaction
  | TagTypeDamage
  | TagTypeDeckDiscard
  | TagTypeDeckDraw
  | TagTypeDeckMisc
  | TagTypeDeckSearch
  | TagTypeDeckShuffle
  | TagTypeDiscardFromPlay
  | TagTypeDiscardPile
  | TagTypeDoom
  | TagTypeDuration
  | TagTypeEnemyDebuff
  | TagTypeEnemyElite
  | TagTypeEnemyEngage
  | TagTypeEnemyMitigation
  | TagTypeEnemyValue
  | TagTypeGainKeyword
  | TagTypeGainResource
  | TagTypeHeal
  | TagTypeLocationConnecting
  | TagTypeLocationMove
  | TagTypeLocationProperty
  | TagTypeLocationShroud
  | TagTypeLocationYour
  | TagTypePlayArea
  | TagTypeRecursion
  | TagTypeSkillTestCondition
  | TagTypeSkillValue
  | TagTypeSlotAdditional
  | TagTypeStatsModBoostInTest
  | TagTypeStatsModBoostPassive
  | TagTypeStatsModPump
  | TagTypeTestInitiate
  | TagTypeTestMisc
  | TagTypeTestResult
  | TagTypeTestless
  | TagTypeTimingAfter
  | TagTypeTimingDuring
  | TagTypeTimingForced
  | TagTypeTimingGame
  | TagTypeTimingPhaseSequence
  | TagTypeTimingSkill
  | TagTypeTimingWhen
  | TagTypeTraitSupport
  | TagTypeUsesStarting
  | TagTypeUsesSupport;
