// This file is auto-generated by script/generate-unions.ts
// Do not edit manually - run 'bun run sync-unions' to regenerate

import type {
  TagActionAdditional,
  TagActionBoldEngage,
  TagActionBoldEvade,
  TagActionBoldFight,
  TagActionBoldInvestigate,
  TagActionBoldMove,
  TagActionBoldParley,
  TagActionBoldResign,
  TagActionLoseAction,
} from "./tags/action/index.js";

import type {
  TagAttachAsset,
  TagAttachEnemy,
  TagAttachLocation,
} from "./tags/attach/index.js";

import type {
  TagAutoEvade,
  TagAutoSuccess,
} from "./tags/auto/index.js";

import type {
  TagBuffCannotAttackYou,
  TagBuffStatsReplace,
} from "./tags/buff/index.js";

import type {
  TagCancelAttack,
  TagCancelChaos,
  TagCancelDamage,
  TagCancelEncounterDraw,
  TagCancelEncounterEffect,
  TagCancelHorror,
  TagCancelRevelation,
} from "./tags/cancel/index.js";

import type {
  TagChaosEffectDoNotReveal,
  TagChaosEffectIgnoreEffect,
  TagChaosEffectIgnoreModifier,
  TagChaosEffectModifier,
  TagChaosEffectResolveChoose,
  TagChaosEffectRevealBeforeEffect,
  TagChaosEffectTreatAsElderSign,
  TagChaosRevealAnotherInstead,
  TagChaosRevealManual,
  TagChaosRevealMore,
  TagChaosRevealTokenAutoFail,
  TagChaosRevealTokenBless,
  TagChaosRevealTokenCultist,
  TagChaosRevealTokenCurse,
  TagChaosRevealTokenElderSign,
  TagChaosRevealTokenElderThing,
  TagChaosRevealTokenSkull,
  TagChaosRevealTokenTablet,
  TagChaosSealToken0,
  TagChaosSealTokenAny,
  TagChaosSealTokenAutoFail,
  TagChaosSealTokenCultist,
  TagChaosSealTokenElderSign,
  TagChaosSealTokenElderThing,
  TagChaosSealTokenSkull,
  TagChaosSealTokenTablet,
} from "./tags/chaos/index.js";

import type {
  TagClueAdditionalAdjacentLocations,
  TagClueAdditionalRevealedLocations,
  TagClueAdditionalThisLocation,
  TagClueDiscoverAnyLocation,
  TagClueDiscoverConnectingLocation,
  TagClueDiscoverYourLocation,
} from "./tags/clue/index.js";

import type {
  TagCostActionDiscardFromHand,
  TagCostActionDiscardSelf,
  TagCostActionExhaustSelf,
  TagCostActionMultiple,
  TagCostActionSpendResource,
  TagCostDamageSelf,
  TagCostDiscardCard,
  TagCostDiscount,
  TagCostFastDiscardSelf,
  TagCostFastExhaustSelf,
  TagCostFastSpendResource,
  TagCostFreeDamageSelf,
  TagCostFreeDiscardSelf,
  TagCostFreeExhaustSelf,
  TagCostFreeSpendCharge,
  TagCostFreeSpendResource,
  TagCostFreeSpendSecret,
  TagCostReactionDamageSelf,
  TagCostReactionDiscardSelf,
  TagCostReactionExhaustSelf,
  TagCostReactionHorrorSelf,
  TagCostReactionSpendCharge,
  TagCostReactionSpendResource,
} from "./tags/cost/index.js";

import type {
  TagDamageInsteadFailRange,
  TagDamageInsteadRange,
  TagDamagePlus,
  TagDamageToInvestigator,
} from "./tags/damage/index.js";

import type {
  TagDeckDiscardCardChoose,
  TagDeckDiscardCardRandom,
  TagDeckDiscardDeck,
  TagDeckDiscardSelf,
  TagDeckDiscardTreachery,
  TagDeckDiscardZeroUses,
  TagDeckDrawInvestigator,
  TagDeckDrawReplaceSelf,
  TagDeckDrawYou,
  TagDeckRestriction,
  TagDeckSearchDiscard,
  TagDeckSearchEncounter,
  TagDeckSearchInvestigator,
  TagDeckSearchYou,
  TagDeckShuffleEncounter,
  TagDeckShufflePlayer,
} from "./tags/deck/index.js";

import type {
  TagDiscardFromPlaySelf,
  TagDiscardFromPlaySelfNoUses,
} from "./tags/discard/index.js";

import type {
  TagDiscardPileToBottomDeck,
  TagDiscardPileToDeck,
  TagDiscardPileToHand,
  TagDiscardPileToTopDeck,
} from "./tags/discard-pile/index.js";

import type {
  TagDoomAdd,
  TagDoomCheck,
  TagDoomRemove,
} from "./tags/doom/index.js";

import type {
  TagDurationEnemyPhase,
  TagDurationNext,
  TagDurationNextSkillTestThisPhase,
  TagDurationNextSkillTestThisTurn,
  TagDurationUntilEndPhase,
  TagDurationUntilEndRound,
  TagDurationUntilEndTurn,
} from "./tags/duration/index.js";

import type {
  TagEnemyCannotMoveIntoLocation,
  TagEnemyDoesNotReady,
  TagEnemyEliteNonEliteOnly,
  TagEnemyEliteReducedEffect,
  TagEnemyEngageEffect,
  TagEnemyEngageEnemy,
  TagEnemyEngageNone,
  TagEnemyEngageNotWithYou,
  TagEnemyEngageRelated,
  TagEnemyEngageWithAnother,
  TagEnemyEngageWithYou,
  TagEnemyMitigationBackToEncounterDeck,
  TagEnemyMitigationDefeat,
  TagEnemyMitigationDiscard,
  TagEnemyValueDamage,
  TagEnemyValueEvade,
  TagEnemyValueEvadeReduction,
  TagEnemyValueFight,
  TagEnemyValueFightReduction,
  TagEnemyValueHorror,
} from "./tags/enemy/index.js";

import type {
  TagGainKeywordAloof,
  TagGainKeywordRetaliate,
  TagGainResourceInvestigator,
  TagGainResourceYou,
} from "./tags/gain/index.js";

import type {
  TagHealDamageAlly,
  TagHealDamageInvestigator,
  TagHealDamageYou,
  TagHealHorrorAlly,
  TagHealHorrorInvestigator,
  TagHealHorrorYou,
} from "./tags/heal/index.js";

import type {
  TagLocationConnectingEnemy,
  TagLocationConnectingInvestigator,
  TagLocationMoveClue,
  TagLocationMoveDamage,
  TagLocationMoveEnemyControl,
  TagLocationMoveEnemyDisplace,
  TagLocationMoveEnemyToYou,
  TagLocationMoveInvestigatorAny,
  TagLocationMoveInvestigatorSelf,
  TagLocationPropertyClueExist,
  TagLocationPropertyClueZero,
  TagLocationPropertyEnemyZero,
  TagLocationShroudDependent,
  TagLocationShroudMinus1,
  TagLocationShroudMinus2,
  TagLocationShroudReduction,
  TagLocationYourAlly,
  TagLocationYourClue,
  TagLocationYourEnemy,
  TagLocationYourInvestigator,
} from "./tags/location/index.js";

import type {
  TagPlayAreaToDeck,
  TagPlayAreaToHand,
} from "./tags/play-area/index.js";

import type {
  TagRecursionAsset,
  TagRecursionEvent,
  TagRecursionSkill,
} from "./tags/recursion/index.js";

import type {
  TagSkillTestConditionFail,
  TagSkillTestConditionSuccessful,
  TagSkillTestConditionSuccessfulDuringAnAttack,
} from "./tags/skill-test-condition/index.js";

import type {
  TagSkillValueFailByDynamic,
  TagSkillValueFailByExactly,
  TagSkillValueFailByOrLess,
  TagSkillValueSucceedByDynamic,
  TagSkillValueSucceedByExactly,
  TagSkillValueSucceedByOrMore,
} from "./tags/skill-value/index.js";

import type {
  TagSlotAdditional,
  TagSlotAdditionalAccessory,
  TagSlotAdditionalAlly,
  TagSlotAdditionalArcane,
  TagSlotAdditionalHand,
} from "./tags/slot/index.js";

import type {
  TagStatsModBoostInTestAgility,
  TagStatsModBoostInTestAny,
  TagStatsModBoostInTestCombat,
  TagStatsModBoostInTestIntellect,
  TagStatsModBoostInTestWillpower,
  TagStatsModBoostPassiveAgility,
  TagStatsModBoostPassiveAny,
  TagStatsModBoostPassiveCombat,
  TagStatsModBoostPassiveIntellect,
  TagStatsModBoostPassiveWillpower,
  TagStatsModPumpCharge,
  TagStatsModPumpResource,
} from "./tags/stats-mod/index.js";

import type {
  TagTestFailBy,
  TagTestInitiateAgility,
  TagTestInitiateCombat,
  TagTestInitiateIntellect,
  TagTestInitiateWillpower,
  TagTestSucceedBy,
  TagTestYouPerform,
} from "./tags/test/index.js";

import type {
  TagTestlessClue,
  TagTestlessDamageAttackingEnemy,
  TagTestlessDamageConnectingLocation,
  TagTestlessDamageYourLocation,
  TagTestlessDamageYourLocationMultiple,
  TagTestlessEvade,
} from "./tags/testless/index.js";

import type {
  TagTimingAfterEnemyAttacks,
  TagTimingAfterEnemyDealDamageInvestigator,
  TagTimingAfterEnemyDealDamageSelf,
  TagTimingAfterEnemyDealDamageYou,
  TagTimingAfterEntersPlay,
  TagTimingAfterSuccessfullyInvestigate,
  TagTimingDuringYourTurn,
  TagTimingForcedEntersLocation,
  TagTimingForcedLeavesPlay,
  TagTimingForcedSpawnYourLocation,
  TagTimingForcedWhenTakeDamage,
  TagTimingForcedWhenTakeHorror,
  TagTimingGameBegins,
  TagTimingGameDrawOpeningHands,
  TagTimingGameEnds,
  TagTimingPhaseEnemyAttacks,
  TagTimingPhaseEnemyBegins,
  TagTimingPhaseEnemyEnds,
  TagTimingPhaseEnemyHunterMove,
  TagTimingPhaseInvestigationBegins,
  TagTimingPhaseInvestigationEnds,
  TagTimingPhaseInvestigationTakeAction,
  TagTimingPhaseInvestigationTurnBegins,
  TagTimingPhaseInvestigationTurnEnds,
  TagTimingPhaseMythosBegins,
  TagTimingPhaseMythosCheckDoom,
  TagTimingPhaseMythosDrawEncounter,
  TagTimingPhaseMythosEnds,
  TagTimingPhaseMythosPlaceDoom,
  TagTimingPhaseUpkeepBegins,
  TagTimingPhaseUpkeepCheckHandSize,
  TagTimingPhaseUpkeepDrawResource,
  TagTimingPhaseUpkeepEnds,
  TagTimingPhaseUpkeepReadyCards,
  TagTimingPhaseUpkeepResetActions,
  TagTimingSkillSt1DetermineSkillType,
  TagTimingSkillSt2CommitCards,
  TagTimingSkillSt3RevealChaosToken,
  TagTimingSkillSt4ApplyChaosEffect,
  TagTimingSkillSt5DetermineSkillValue,
  TagTimingSkillSt6DetermineResult,
  TagTimingSkillSt7ApplyResults,
  TagTimingSkillSt8TestEnds,
  TagTimingWhenDefeatEnemy,
  TagTimingWhenEnemyAttacks,
  TagTimingWhenEnemySpawnsYourLocation,
} from "./tags/timing/index.js";

import type {
  TagTraitSupportAlly,
  TagTraitSupportFirearm,
  TagTraitSupportIllicit,
  TagTraitSupportInnate,
  TagTraitSupportInsight,
  TagTraitSupportItem,
  TagTraitSupportMelee,
  TagTraitSupportPracticed,
  TagTraitSupportRanged,
  TagTraitSupportRelic,
  TagTraitSupportScience,
  TagTraitSupportSpell,
  TagTraitSupportSpirit,
  TagTraitSupportSupply,
  TagTraitSupportTactic,
  TagTraitSupportTome,
  TagTraitSupportTrick,
  TagTraitSupportWeapon,
} from "./tags/trait/index.js";

import type {
  TagUsesStartingAmmo,
  TagUsesStartingCharge,
  TagUsesStartingEvidence,
  TagUsesStartingSecret,
  TagUsesStartingSupply,
  TagUsesSupportAmmo,
  TagUsesSupportCharge,
  TagUsesSupportEvidence,
  TagUsesSupportSecret,
  TagUsesSupportSupply,
} from "./tags/uses/index.js";

/**
 * Union type of all possible tag instances.
 * This replaces the old string-based Tag type.
 */
export type Tag =
  // Action tags
  TagActionAdditional
  | TagActionBoldEngage
  | TagActionBoldEvade
  | TagActionBoldFight
  | TagActionBoldInvestigate
  | TagActionBoldMove
  | TagActionBoldParley
  | TagActionBoldResign
  | TagActionLoseAction
  // Attach tags
  | TagAttachAsset
  | TagAttachEnemy
  | TagAttachLocation
  // Auto tags
  | TagAutoEvade
  | TagAutoSuccess
  // Buff tags
  | TagBuffCannotAttackYou
  | TagBuffStatsReplace
  // Cancel tags
  | TagCancelAttack
  | TagCancelChaos
  | TagCancelDamage
  | TagCancelEncounterDraw
  | TagCancelEncounterEffect
  | TagCancelHorror
  | TagCancelRevelation
  // Chaos tags
  | TagChaosEffectDoNotReveal
  | TagChaosEffectIgnoreEffect
  | TagChaosEffectIgnoreModifier
  | TagChaosEffectModifier
  | TagChaosEffectResolveChoose
  | TagChaosEffectRevealBeforeEffect
  | TagChaosEffectTreatAsElderSign
  | TagChaosRevealAnotherInstead
  | TagChaosRevealManual
  | TagChaosRevealMore
  | TagChaosRevealTokenAutoFail
  | TagChaosRevealTokenBless
  | TagChaosRevealTokenCultist
  | TagChaosRevealTokenCurse
  | TagChaosRevealTokenElderSign
  | TagChaosRevealTokenElderThing
  | TagChaosRevealTokenSkull
  | TagChaosRevealTokenTablet
  | TagChaosSealToken0
  | TagChaosSealTokenAny
  | TagChaosSealTokenAutoFail
  | TagChaosSealTokenCultist
  | TagChaosSealTokenElderSign
  | TagChaosSealTokenElderThing
  | TagChaosSealTokenSkull
  | TagChaosSealTokenTablet
  // Clue tags
  | TagClueAdditionalAdjacentLocations
  | TagClueAdditionalRevealedLocations
  | TagClueAdditionalThisLocation
  | TagClueDiscoverAnyLocation
  | TagClueDiscoverConnectingLocation
  | TagClueDiscoverYourLocation
  // Cost tags
  | TagCostActionDiscardFromHand
  | TagCostActionDiscardSelf
  | TagCostActionExhaustSelf
  | TagCostActionMultiple
  | TagCostActionSpendResource
  | TagCostDamageSelf
  | TagCostDiscardCard
  | TagCostDiscount
  | TagCostFastDiscardSelf
  | TagCostFastExhaustSelf
  | TagCostFastSpendResource
  | TagCostFreeDamageSelf
  | TagCostFreeDiscardSelf
  | TagCostFreeExhaustSelf
  | TagCostFreeSpendCharge
  | TagCostFreeSpendResource
  | TagCostFreeSpendSecret
  | TagCostReactionDamageSelf
  | TagCostReactionDiscardSelf
  | TagCostReactionExhaustSelf
  | TagCostReactionHorrorSelf
  | TagCostReactionSpendCharge
  | TagCostReactionSpendResource
  // Damage tags
  | TagDamageInsteadFailRange
  | TagDamageInsteadRange
  | TagDamagePlus
  | TagDamageToInvestigator
  // Deck tags
  | TagDeckDiscardCardChoose
  | TagDeckDiscardCardRandom
  | TagDeckDiscardDeck
  | TagDeckDiscardSelf
  | TagDeckDiscardTreachery
  | TagDeckDiscardZeroUses
  | TagDeckDrawInvestigator
  | TagDeckDrawReplaceSelf
  | TagDeckDrawYou
  | TagDeckRestriction
  | TagDeckSearchDiscard
  | TagDeckSearchEncounter
  | TagDeckSearchInvestigator
  | TagDeckSearchYou
  | TagDeckShuffleEncounter
  | TagDeckShufflePlayer
  // Discard tags
  | TagDiscardFromPlaySelf
  | TagDiscardFromPlaySelfNoUses
  // Discard Pile tags
  | TagDiscardPileToBottomDeck
  | TagDiscardPileToDeck
  | TagDiscardPileToHand
  | TagDiscardPileToTopDeck
  // Doom tags
  | TagDoomAdd
  | TagDoomCheck
  | TagDoomRemove
  // Duration tags
  | TagDurationEnemyPhase
  | TagDurationNext
  | TagDurationNextSkillTestThisPhase
  | TagDurationNextSkillTestThisTurn
  | TagDurationUntilEndPhase
  | TagDurationUntilEndRound
  | TagDurationUntilEndTurn
  // Enemy tags
  | TagEnemyCannotMoveIntoLocation
  | TagEnemyDoesNotReady
  | TagEnemyEliteNonEliteOnly
  | TagEnemyEliteReducedEffect
  | TagEnemyEngageEffect
  | TagEnemyEngageEnemy
  | TagEnemyEngageNone
  | TagEnemyEngageNotWithYou
  | TagEnemyEngageRelated
  | TagEnemyEngageWithAnother
  | TagEnemyEngageWithYou
  | TagEnemyMitigationBackToEncounterDeck
  | TagEnemyMitigationDefeat
  | TagEnemyMitigationDiscard
  | TagEnemyValueDamage
  | TagEnemyValueEvade
  | TagEnemyValueEvadeReduction
  | TagEnemyValueFight
  | TagEnemyValueFightReduction
  | TagEnemyValueHorror
  // Gain tags
  | TagGainKeywordAloof
  | TagGainKeywordRetaliate
  | TagGainResourceInvestigator
  | TagGainResourceYou
  // Heal tags
  | TagHealDamageAlly
  | TagHealDamageInvestigator
  | TagHealDamageYou
  | TagHealHorrorAlly
  | TagHealHorrorInvestigator
  | TagHealHorrorYou
  // Location tags
  | TagLocationConnectingEnemy
  | TagLocationConnectingInvestigator
  | TagLocationMoveClue
  | TagLocationMoveDamage
  | TagLocationMoveEnemyControl
  | TagLocationMoveEnemyDisplace
  | TagLocationMoveEnemyToYou
  | TagLocationMoveInvestigatorAny
  | TagLocationMoveInvestigatorSelf
  | TagLocationPropertyClueExist
  | TagLocationPropertyClueZero
  | TagLocationPropertyEnemyZero
  | TagLocationShroudDependent
  | TagLocationShroudMinus1
  | TagLocationShroudMinus2
  | TagLocationShroudReduction
  | TagLocationYourAlly
  | TagLocationYourClue
  | TagLocationYourEnemy
  | TagLocationYourInvestigator
  // Play Area tags
  | TagPlayAreaToDeck
  | TagPlayAreaToHand
  // Recursion tags
  | TagRecursionAsset
  | TagRecursionEvent
  | TagRecursionSkill
  // Skill Test Condition tags
  | TagSkillTestConditionFail
  | TagSkillTestConditionSuccessful
  | TagSkillTestConditionSuccessfulDuringAnAttack
  // Skill Value tags
  | TagSkillValueFailByDynamic
  | TagSkillValueFailByExactly
  | TagSkillValueFailByOrLess
  | TagSkillValueSucceedByDynamic
  | TagSkillValueSucceedByExactly
  | TagSkillValueSucceedByOrMore
  // Slot tags
  | TagSlotAdditional
  | TagSlotAdditionalAccessory
  | TagSlotAdditionalAlly
  | TagSlotAdditionalArcane
  | TagSlotAdditionalHand
  // Stats Mod tags
  | TagStatsModBoostInTestAgility
  | TagStatsModBoostInTestAny
  | TagStatsModBoostInTestCombat
  | TagStatsModBoostInTestIntellect
  | TagStatsModBoostInTestWillpower
  | TagStatsModBoostPassiveAgility
  | TagStatsModBoostPassiveAny
  | TagStatsModBoostPassiveCombat
  | TagStatsModBoostPassiveIntellect
  | TagStatsModBoostPassiveWillpower
  | TagStatsModPumpCharge
  | TagStatsModPumpResource
  // Test tags
  | TagTestFailBy
  | TagTestInitiateAgility
  | TagTestInitiateCombat
  | TagTestInitiateIntellect
  | TagTestInitiateWillpower
  | TagTestSucceedBy
  | TagTestYouPerform
  // Testless tags
  | TagTestlessClue
  | TagTestlessDamageAttackingEnemy
  | TagTestlessDamageConnectingLocation
  | TagTestlessDamageYourLocation
  | TagTestlessDamageYourLocationMultiple
  | TagTestlessEvade
  // Timing tags
  | TagTimingAfterEnemyAttacks
  | TagTimingAfterEnemyDealDamageInvestigator
  | TagTimingAfterEnemyDealDamageSelf
  | TagTimingAfterEnemyDealDamageYou
  | TagTimingAfterEntersPlay
  | TagTimingAfterSuccessfullyInvestigate
  | TagTimingDuringYourTurn
  | TagTimingForcedEntersLocation
  | TagTimingForcedLeavesPlay
  | TagTimingForcedSpawnYourLocation
  | TagTimingForcedWhenTakeDamage
  | TagTimingForcedWhenTakeHorror
  | TagTimingGameBegins
  | TagTimingGameDrawOpeningHands
  | TagTimingGameEnds
  | TagTimingPhaseEnemyAttacks
  | TagTimingPhaseEnemyBegins
  | TagTimingPhaseEnemyEnds
  | TagTimingPhaseEnemyHunterMove
  | TagTimingPhaseInvestigationBegins
  | TagTimingPhaseInvestigationEnds
  | TagTimingPhaseInvestigationTakeAction
  | TagTimingPhaseInvestigationTurnBegins
  | TagTimingPhaseInvestigationTurnEnds
  | TagTimingPhaseMythosBegins
  | TagTimingPhaseMythosCheckDoom
  | TagTimingPhaseMythosDrawEncounter
  | TagTimingPhaseMythosEnds
  | TagTimingPhaseMythosPlaceDoom
  | TagTimingPhaseUpkeepBegins
  | TagTimingPhaseUpkeepCheckHandSize
  | TagTimingPhaseUpkeepDrawResource
  | TagTimingPhaseUpkeepEnds
  | TagTimingPhaseUpkeepReadyCards
  | TagTimingPhaseUpkeepResetActions
  | TagTimingSkillSt1DetermineSkillType
  | TagTimingSkillSt2CommitCards
  | TagTimingSkillSt3RevealChaosToken
  | TagTimingSkillSt4ApplyChaosEffect
  | TagTimingSkillSt5DetermineSkillValue
  | TagTimingSkillSt6DetermineResult
  | TagTimingSkillSt7ApplyResults
  | TagTimingSkillSt8TestEnds
  | TagTimingWhenDefeatEnemy
  | TagTimingWhenEnemyAttacks
  | TagTimingWhenEnemySpawnsYourLocation
  // Trait tags
  | TagTraitSupportAlly
  | TagTraitSupportFirearm
  | TagTraitSupportIllicit
  | TagTraitSupportInnate
  | TagTraitSupportInsight
  | TagTraitSupportItem
  | TagTraitSupportMelee
  | TagTraitSupportPracticed
  | TagTraitSupportRanged
  | TagTraitSupportRelic
  | TagTraitSupportScience
  | TagTraitSupportSpell
  | TagTraitSupportSpirit
  | TagTraitSupportSupply
  | TagTraitSupportTactic
  | TagTraitSupportTome
  | TagTraitSupportTrick
  | TagTraitSupportWeapon
  // Uses tags
  | TagUsesStartingAmmo
  | TagUsesStartingCharge
  | TagUsesStartingEvidence
  | TagUsesStartingSecret
  | TagUsesStartingSupply
  | TagUsesSupportAmmo
  | TagUsesSupportCharge
  | TagUsesSupportEvidence
  | TagUsesSupportSecret
  | TagUsesSupportSupply
;
