import { EncounterSet } from '@5argon/arkham-kohaku';
import * as m from '../paraglide/messages.js';

/**
 * Get the translated name for an encounter set.
 * Uses Paraglide messages to return the localized encounter set name.
 */
export function encounterSetName(encounterSet: EncounterSet): string {
  switch (encounterSet) {
    // Core Set
    case EncounterSet.AgentsOfCthulhu:
      return m.campaignRegularCoreSetEncounterAgentsOfCthulhu();
    case EncounterSet.AgentsOfHastur:
      return m.campaignRegularCoreSetEncounterAgentsOfHastur();
    case EncounterSet.AgentsOfShubniggurath:
      return m.campaignRegularCoreSetEncounterAgentsOfShubNiggurath();
    case EncounterSet.AgentsOfYogsothoth:
      return m.campaignRegularCoreSetEncounterAgentsOfYogSothoth();
    case EncounterSet.AncientEvils:
      return m.campaignRegularCoreSetEncounterAncientEvils();
    case EncounterSet.ChillingCold:
      return m.campaignRegularCoreSetEncounterChillingCold();
    case EncounterSet.CultOfUmrdhoth:
      return m.campaignRegularCoreSetEncounterCultOfUmrdhoth();
    case EncounterSet.DarkCult:
      return m.campaignRegularCoreSetEncounterDarkCult();
    case EncounterSet.Ghouls:
      return m.campaignRegularCoreSetEncounterGhouls();
    case EncounterSet.LockedDoors:
      return m.campaignRegularCoreSetEncounterLockedDoors();
    case EncounterSet.Nightgaunts:
      return m.campaignRegularCoreSetEncounterNightgaunts();
    case EncounterSet.Rats:
      return m.campaignRegularCoreSetEncounterRats();
    case EncounterSet.StrikingFear:
      return m.campaignRegularCoreSetEncounterStrikingFear();
    case EncounterSet.TheDevourerBelow:
      return m.campaignRegularNightOfTheZealotScenarioTheDevourerBelow();
    case EncounterSet.TheGathering:
      return m.campaignRegularNightOfTheZealotScenarioTheGathering();
    case EncounterSet.TheMidnightMasks:
      return m.campaignRegularNightOfTheZealotScenarioTheMidnightMasks();

    // The Dunwich Legacy
    case EncounterSet.ArmitagesFate:
      return m.campaignRegularTheDunwichLegacyEncounterArmitagesFate();
    case EncounterSet.BadLuck:
      return m.campaignRegularTheDunwichLegacyEncounterBadLuck();
    case EncounterSet.BeastThralls:
      return m.campaignRegularTheDunwichLegacyEncounterBeastThralls();
    case EncounterSet.BishopsThralls:
      return m.campaignRegularTheDunwichLegacyEncounterBishopsThralls();
    case EncounterSet.BloodOnTheAltar:
      return m.campaignRegularTheDunwichLegacyScenarioBloodOnTheAltar();
    case EncounterSet.Dunwich:
      return m.campaignRegularTheDunwichLegacyEncounterDunwich();
    case EncounterSet.TheEssexCountyExpress:
      return m.campaignRegularTheDunwichLegacyScenarioTheEssexCountyExpress();
    case EncounterSet.ExtracurricularActivity:
      return m.campaignRegularTheDunwichLegacyScenarioExtracurricularActivity();
    case EncounterSet.HideousAbominations:
      return m.campaignRegularTheDunwichLegacyEncounterHideousAbominations();
    case EncounterSet.LostInTimeAndSpace:
      return m.campaignRegularTheDunwichLegacyScenarioLostInTimeAndSpace();
    case EncounterSet.NaomisCrew:
      return m.campaignRegularTheDunwichLegacyEncounterNaomisCrew();
    case EncounterSet.Sorcery:
      return m.campaignRegularTheDunwichLegacyEncounterSorcery();
    case EncounterSet.TheBeyond:
      return m.campaignRegularTheDunwichLegacyEncounterTheBeyond();
    case EncounterSet.TheHouseAlwaysWins:
      return m.campaignRegularTheDunwichLegacyScenarioTheHouseAlwaysWins();
    case EncounterSet.TheMiskatonicMuseum:
      return m.campaignRegularTheDunwichLegacyScenarioTheMiskatonicMuseum();
    case EncounterSet.UndimensionedAndUnseen:
      return m.campaignRegularTheDunwichLegacyScenarioUndimensionedAndUnseen();
    case EncounterSet.WhereDoomAwaits:
      return m.campaignRegularTheDunwichLegacyScenarioWhereDoomAwaits();
    case EncounterSet.Whippoorwills:
      return m.campaignRegularTheDunwichLegacyEncounterWhippoorwills();

    // Edge of the Earth
    case EncounterSet.AgentsOfTheUnknown:
      return m.campaignRegularEdgeOfTheEarthEncounterAgentsOfTheUnknown();
    case EncounterSet.CityOfTheElderThings:
      return m.campaignRegularEdgeOfTheEarthScenarioCityOfTheElderThings();
    case EncounterSet.CreaturesInTheIce:
      return m.campaignRegularEdgeOfTheEarthEncounterCreaturesInTheIce();
    case EncounterSet.DeadlyWeather:
      return m.campaignRegularEdgeOfTheEarthEncounterDeadlyWeather();
    case EncounterSet.ElderThings:
      return m.campaignRegularEdgeOfTheEarthEncounterElderThings();
    case EncounterSet.ExpeditionTeam:
      return m.campaignRegularEdgeOfTheEarthEncounterExpeditionTeam();
    case EncounterSet.FatalMirage:
      return m.campaignRegularEdgeOfTheEarthScenarioFatalMirage();
    case EncounterSet.HazardsOfAntarctica:
      return m.campaignRegularEdgeOfTheEarthEncounterHazardsOfAntarctica();
    case EncounterSet.IceAndDeath:
      return m.campaignRegularEdgeOfTheEarthScenarioIceAndDeath();
    case EncounterSet.LeftBehind:
      return m.campaignRegularEdgeOfTheEarthEncounterLeftBehind();
    case EncounterSet.LostInTheNight:
      return m.campaignRegularEdgeOfTheEarthEncounterLostInTheNight();
    case EncounterSet.MemorialsOfTheLost:
      return m.campaignRegularEdgeOfTheEarthEncounterMemorialsOfTheLost();
    case EncounterSet.Miasma:
      return m.campaignRegularEdgeOfTheEarthEncounterMiasma();
    case EncounterSet.NamelessHorrors:
      return m.campaignRegularEdgeOfTheEarthEncounterNamelessHorrors();
    case EncounterSet.Penguins:
      return m.campaignRegularEdgeOfTheEarthEncounterPenguins();
    case EncounterSet.SeepingNightmares:
      return m.campaignRegularEdgeOfTheEarthEncounterSeepingNightmares();
    case EncounterSet.Shoggoths:
      return m.campaignRegularEdgeOfTheEarthEncounterShoggoths();
    case EncounterSet.SilenceAndMystery:
      return m.campaignRegularEdgeOfTheEarthEncounterSilenceAndMystery();
    case EncounterSet.StirringInTheDeep:
      return m.campaignRegularEdgeOfTheEarthEncounterStirringInTheDeep();
    case EncounterSet.Tekelili:
      return m.campaignRegularEdgeOfTheEarthEncounterTekelili();
    case EncounterSet.TheCrash:
      return m.campaignRegularEdgeOfTheEarthEncounterTheCrash();
    case EncounterSet.TheGreatSeal:
      return m.campaignRegularEdgeOfTheEarthEncounterTheGreatSeal();
    case EncounterSet.TheHeartOfMadness:
      return m.campaignRegularEdgeOfTheEarthScenarioTheHeartOfMadness();
    case EncounterSet.ToTheForbiddenPeaks:
      return m.campaignRegularEdgeOfTheEarthScenarioToTheForbiddenPeaks();

    // The Feast of Hemlock Vale
    case EncounterSet.AgentsOfTheColour:
      return m.campaignRegularTheFeastOfHemlockValeEncounterAgentsOfTheColour();
    case EncounterSet.Blight:
      return m.campaignRegularTheFeastOfHemlockValeEncounterBlight();
    case EncounterSet.DayOfRain:
      return m.campaignRegularTheFeastOfHemlockValeEncounterDayOfRain();
    case EncounterSet.DayOfRest:
      return m.campaignRegularTheFeastOfHemlockValeEncounterDayOfRest();
    case EncounterSet.DayOfTheFeast:
      return m.campaignRegularTheFeastOfHemlockValeEncounterDayOfTheFeast();
    case EncounterSet.FateOfTheVale:
      return m.campaignRegularTheFeastOfHemlockValeScenarioFateOfTheVale();
    case EncounterSet.Fire:
      return m.campaignRegularTheFeastOfHemlockValeEncounterFire();
    case EncounterSet.Heirlooms:
      return m.campaignRegularTheFeastOfHemlockValeEncounterHeirlooms();
    case EncounterSet.HemlockHouse:
      return m.campaignRegularTheFeastOfHemlockValeScenarioHemlockHouse();
    case EncounterSet.HorrorsInTheRock:
      return m.campaignRegularTheFeastOfHemlockValeEncounterHorrorsInTheRock();
    case EncounterSet.Mutations:
      return m.campaignRegularTheFeastOfHemlockValeEncounterMutations();
    case EncounterSet.Myconids:
      return m.campaignRegularTheFeastOfHemlockValeEncounterMyconids();
    case EncounterSet.Refractions:
      return m.campaignRegularTheFeastOfHemlockValeEncounterRefractions();
    case EncounterSet.Residents:
      return m.campaignRegularTheFeastOfHemlockValeEncounterResidents();
    case EncounterSet.TheFinalDay:
      return m.campaignRegularTheFeastOfHemlockValeEncounterTheFinalDay();
    case EncounterSet.TheFirstDay:
      return m.campaignRegularTheFeastOfHemlockValeEncounterTheFirstDay();
    case EncounterSet.TheForest:
      return m.campaignRegularTheFeastOfHemlockValeEncounterTheForest();
    case EncounterSet.TheLongestNight:
      return m.campaignRegularTheFeastOfHemlockValeScenarioTheLongestNight();
    case EncounterSet.TheLostSister:
      return m.campaignRegularTheFeastOfHemlockValeScenarioTheLostSister();
    case EncounterSet.TheSecondDay:
      return m.campaignRegularTheFeastOfHemlockValeEncounterTheSecondDay();
    case EncounterSet.TheSilentHeath:
      return m.campaignRegularTheFeastOfHemlockValeScenarioTheSilentHeath();
    case EncounterSet.TheThingInTheDepths:
      return m.campaignRegularTheFeastOfHemlockValeScenarioTheThingInTheDepths();
    case EncounterSet.TheTwistedHollow:
      return m.campaignRegularTheFeastOfHemlockValeScenarioTheTwistedHollow();
    case EncounterSet.TheVale:
      return m.campaignRegularTheFeastOfHemlockValeEncounterTheVale();
    case EncounterSet.Transfiguration:
      return m.campaignRegularTheFeastOfHemlockValeEncounterTransfiguration();
    case EncounterSet.WrittenInRock:
      return m.campaignRegularTheFeastOfHemlockValeScenarioWrittenInRock();

    // Parallel
    case EncounterSet.AllOrNothing:
      return m.challengeScenarioNameAllOrNothing();
    case EncounterSet.BadBlood:
      return m.challengeScenarioNameBadBlood();
    case EncounterSet.ByTheBook:
      return m.challengeScenarioNameByTheBook();
    case EncounterSet.LaidToRest:
      return m.challengeScenarioNameLaidToRest();
    case EncounterSet.ReadOrDie:
      return m.challengeScenarioNameReadOrDie();
    case EncounterSet.RedTideRising:
      return m.challengeScenarioNameRedTideRising();
    case EncounterSet.RelicsOfThePast:
      return m.challengeScenarioNameRelicsOfThePast();

    // The Path to Carcosa
    case EncounterSet.APhantomOfTruth:
      return m.campaignRegularThePathToCarcosaScenarioAPhantomOfTruth();
    case EncounterSet.BlackStarsRise:
      return m.campaignRegularThePathToCarcosaScenarioBlackStarsRise();
    case EncounterSet.Byakhee:
      return m.campaignRegularThePathToCarcosaEncounterByakhee();
    case EncounterSet.CultOfTheYellowSign:
      return m.campaignRegularThePathToCarcosaEncounterCultOfTheYellowSign();
    case EncounterSet.CurtainCall:
      return m.campaignRegularThePathToCarcosaScenarioCurtainCall();
    case EncounterSet.DecayAndFilth:
      return m.campaignRegularThePathToCarcosaEncounterDecayFilth();
    case EncounterSet.Delusions:
      return m.campaignRegularThePathToCarcosaEncounterDelusions();
    case EncounterSet.DimCarcosa:
      return m.campaignRegularThePathToCarcosaScenarioDimCarcosa();
    case EncounterSet.EchoesOfThePast:
      return m.campaignRegularThePathToCarcosaScenarioEchoesOfThePast();
    case EncounterSet.EvilPortents:
      return m.campaignRegularThePathToCarcosaEncounterEvilPortents();
    case EncounterSet.TheFloodBelow:
      return m.campaignRegularThePathToCarcosaEncounterTheFloodBelow();
    case EncounterSet.HastursGift:
      return m.campaignRegularThePathToCarcosaEncounterHastursGift();
    case EncounterSet.Hauntings:
      return m.campaignRegularThePathToCarcosaEncounterHauntings();
    case EncounterSet.InhabitantsOfCarcosa:
      return m.campaignRegularThePathToCarcosaEncounterInhabitantsOfCarcosa();
    case EncounterSet.TheStranger:
      return m.campaignRegularThePathToCarcosaEncounterTheStranger();
    case EncounterSet.TheLastKing:
      return m.campaignRegularThePathToCarcosaScenarioTheLastKing();
    case EncounterSet.ThePallidMask:
      return m.campaignRegularThePathToCarcosaScenarioThePallidMask();
    case EncounterSet.TheUnspeakableOath:
      return m.campaignRegularThePathToCarcosaScenarioTheUnspeakableOath();
    case EncounterSet.TheVortexAbove:
      return m.campaignRegularThePathToCarcosaEncounterTheVortexAbove();

    // The Circle Undone
    case EncounterSet.AgentsOfAzathoth:
      return m.campaignRegularTheCircleUndoneEncounterAgentsOfAzathoth();
    case EncounterSet.AnettesCoven:
      return m.campaignRegularTheCircleUndoneEncounterAnettesCoven();
    case EncounterSet.AtDeathsDoorstep:
      return m.campaignRegularTheCircleUndoneScenarioAtDeathsDoorstep();
    case EncounterSet.BeforeTheBlackThrone:
      return m.campaignRegularTheCircleUndoneScenarioBeforeTheBlackThrone();
    case EncounterSet.CityOfSins:
      return m.campaignRegularTheCircleUndoneEncounterCityOfSins();
    case EncounterSet.DisappearanceAtTheTwilightEstate:
      return m.campaignRegularTheCircleUndoneScenarioDisappearanceAtTheTwilightEstate();
    case EncounterSet.ForTheGreaterGood:
      return m.campaignRegularTheCircleUndoneScenarioForTheGreaterGood();
    case EncounterSet.InTheClutchesOfChaos:
      return m.campaignRegularTheCircleUndoneScenarioInTheClutchesOfChaos();
    case EncounterSet.InexorableFate:
      return m.campaignRegularTheCircleUndoneEncounterInexorableFate();
    case EncounterSet.MusicOfTheDamned:
      return m.campaignRegularTheCircleUndoneEncounterMusicOfTheDamned();
    case EncounterSet.RealmOfDeath:
      return m.campaignRegularTheCircleUndoneEncounterRealmOfDeath();
    case EncounterSet.SecretsOfTheUniverse:
      return m.campaignRegularTheCircleUndoneEncounterSecretsOfTheUniverse();
    case EncounterSet.SilverTwilightLodge:
      return m.campaignRegularTheCircleUndoneEncounterSilverTwilightLodge();
    case EncounterSet.SpectralPredators:
      return m.campaignRegularTheCircleUndoneEncounterSpectralPredators();
    case EncounterSet.TheSecretName:
      return m.campaignRegularTheCircleUndoneScenarioTheSecretName();
    case EncounterSet.TheWagesOfSin:
      return m.campaignRegularTheCircleUndoneScenarioTheWagesOfSin();
    case EncounterSet.TheWatcher:
      return m.campaignRegularTheCircleUndoneEncounterTheWatcher();
    case EncounterSet.TheWitchingHour:
      return m.campaignRegularTheCircleUndoneScenarioTheWitchingHour();
    case EncounterSet.TrappedSpirits:
      return m.campaignRegularTheCircleUndoneEncounterTrappedSpirits();
    case EncounterSet.UnionAndDisillusion:
      return m.campaignRegularTheCircleUndoneScenarioUnionAndDisillusion();
    case EncounterSet.Witchcraft:
      return m.campaignRegularTheCircleUndoneEncounterWitchcraft();

    // The Drowned City
    case EncounterSet.AlienMachinery:
      return m.campaignRegularTheDrownedCityEncounterAlienMachinery();
    case EncounterSet.CosmicLegacy:
      return m.campaignRegularTheDrownedCityEncounterCosmicLegacy();
    case EncounterSet.CourtOfTheAncients:
      return m.campaignRegularTheDrownedCityScenarioCourtOfTheAncients();
    case EncounterSet.DeepOnes:
      return m.campaignRegularTheDrownedCityEncounterDeepOnes();
    case EncounterSet.Domination:
      return m.campaignRegularTheDrownedCityEncounterDomination();
    case EncounterSet.Dreams:
      return m.campaignRegularTheDrownedCityEncounterDreams();
    case EncounterSet.ElderMist:
      return m.campaignRegularTheDrownedCityEncounterElderMist();
    case EncounterSet.ObsidianCanyons:
      return m.campaignRegularTheDrownedCityScenarioObsidianCanyons();
    case EncounterSet.OneLastJob:
      return m.campaignRegularTheDrownedCityScenarioOneLastJob();
    case EncounterSet.Pilgrims:
      return m.campaignRegularTheDrownedCityEncounterPilgrims();
    case EncounterSet.Rlyeh:
      return m.campaignRegularTheDrownedCityEncounterRlyeh();
    case EncounterSet.SepulchreOfTheSleeper:
      return m.campaignRegularTheDrownedCityScenarioSepulchreOfTheSleeper();
    case EncounterSet.StarSpawn:
      return m.campaignRegularTheDrownedCityEncounterStarSpawn();
    case EncounterSet.Stowaways:
      return m.campaignRegularTheDrownedCityEncounterStowaways();
    case EncounterSet.Tasks:
      return m.campaignRegularTheDrownedCityEncounterTasks();
    case EncounterSet.TdcExpedition:
      return m.campaignRegularTheDrownedCityEncounterExpedition();
    case EncounterSet.TdcFlood:
      return m.campaignRegularTheDrownedCityEncounterFlood();
    case EncounterSet.TheApiary:
      return m.campaignRegularTheDrownedCityScenarioTheApiary();
    case EncounterSet.TheDoomOfArkhamPart1:
      return m.campaignRegularTheDrownedCityScenarioTheDoomOfArkhamPartI();
    case EncounterSet.TheDoomOfArkhamPart2:
      return m.campaignRegularTheDrownedCityScenarioTheDoomOfArkhamPartII();
    case EncounterSet.TheDrownedQuarter:
      return m.campaignRegularTheDrownedCityScenarioTheDrownedQuarter();
    case EncounterSet.TheGrandVault:
      return m.campaignRegularTheDrownedCityScenarioTheGrandVault();
    case EncounterSet.TheInescapable:
      return m.campaignRegularTheDrownedCityEncounterTheInescapable();
    case EncounterSet.TheWesternWall:
      return m.campaignRegularTheDrownedCityScenarioTheWesternWall();
    case EncounterSet.UnderseaCreatures:
      return m.campaignRegularTheDrownedCityEncounterUnderseaCreatures();

    // The Dream-Eaters
    case EncounterSet.AgentsOfAtlachNacha:
      return m.campaignRegularTheDreamEatersEncounterAgentsOfAtlachNacha();
    case EncounterSet.AgentsOfNyarlathotep:
      return m.campaignRegularTheDreamEatersEncounterAgentsOfNyarlathotep();
    case EncounterSet.AThousandShapesOfHorror:
      return m.campaignRegularTheDreamEatersScenarioAThousandShapesOfHorror();
    case EncounterSet.BeyondTheGatesOfSleep:
      return m.campaignRegularTheDreamEatersScenarioBeyondTheGatesOfSleep();
    case EncounterSet.Corsairs:
      return m.campaignRegularTheDreamEatersEncounterCorsairs();
    case EncounterSet.CreaturesOfTheUnderworld:
      return m.campaignRegularTheDreamEatersEncounterCreaturesOfTheUnderworld();
    case EncounterSet.DarkSideOfTheMoon:
      return m.campaignRegularTheDreamEatersScenarioDarkSideOfTheMoon();
    case EncounterSet.DescentIntoThePitch:
      return m.campaignRegularTheDreamEatersEncounterDescentIntoThePitch();
    case EncounterSet.DreamersCurse:
      return m.campaignRegularTheDreamEatersEncounterDreamersCurse();
    case EncounterSet.Dreamlands:
      return m.campaignRegularTheDreamEatersEncounterDreamlands();
    case EncounterSet.MergingRealities:
      return m.campaignRegularTheDreamEatersEncounterMergingRealities();
    case EncounterSet.PointOfNoReturn:
      return m.campaignRegularTheDreamEatersScenarioPointOfNoReturn();
    case EncounterSet.Spiders:
      return m.campaignRegularTheDreamEatersEncounterSpiders();
    case EncounterSet.TerrorOfTheVale:
      return m.campaignRegularTheDreamEatersEncounterTerrorOfTheVale();
    case EncounterSet.TheSearchForKadath:
      return m.campaignRegularTheDreamEatersScenarioTheSearchForKadath();
    case EncounterSet.WakingNightmare:
      return m.campaignRegularTheDreamEatersScenarioWakingNightmare();
    case EncounterSet.WeaverOfTheCosmos:
      return m.campaignRegularTheDreamEatersScenarioWeaverOfTheCosmos();
    case EncounterSet.WhereTheGodsDwell:
      return m.campaignRegularTheDreamEatersScenarioWhereTheGodsDwell();
    case EncounterSet.WhispersOfHypnos:
      return m.campaignRegularTheDreamEatersEncounterWhispersOfHypnos();
    case EncounterSet.Zoogs:
      return m.campaignRegularTheDreamEatersEncounterZoogs();

    // The Forgotten Age
    case EncounterSet.AgentsOfYig:
      return m.campaignRegularTheForgottenAgeEncounterAgentsOfYig();
    case EncounterSet.Expedition:
      return m.campaignRegularTheForgottenAgeEncounterExpedition();
    case EncounterSet.TheDoomOfEztli:
      return m.campaignRegularTheForgottenAgeScenarioTheDoomOfEztli();
    case EncounterSet.TemporalFlux:
      return m.campaignRegularTheForgottenAgeEncounterTemporalFlux();
    case EncounterSet.GuardiansOfTime:
      return m.campaignRegularTheForgottenAgeEncounterGuardiansOfTime();
    case EncounterSet.HeartOfTheElders:
      return m.campaignRegularTheForgottenAgeScenarioHeartOfTheElders();
    case EncounterSet.Knyan:
      return m.campaignRegularTheForgottenAgeEncounterKnyan();
    case EncounterSet.PillarsOfJudgment:
      return m.campaignRegularTheForgottenAgeEncounterPillarsOfJudgment();
    case EncounterSet.PnakoticBrotherhood:
      return m.campaignRegularTheForgottenAgeEncounterPnakoticBrotherhood();
    case EncounterSet.Poison:
      return m.campaignRegularTheForgottenAgeEncounterPoison();
    case EncounterSet.Rainforest:
      return m.campaignRegularTheForgottenAgeEncounterRainforest();
    case EncounterSet.ForgottenRuins:
      return m.campaignRegularTheForgottenAgeEncounterForgottenRuins();
    case EncounterSet.Serpents:
      return m.campaignRegularTheForgottenAgeEncounterSerpents();
    case EncounterSet.ShatteredAeons:
      return m.campaignRegularTheForgottenAgeScenarioShatteredAeons();
    case EncounterSet.TheBoundaryBeyond:
      return m.campaignRegularTheForgottenAgeScenarioTheBoundaryBeyond();
    case EncounterSet.TheCityOfArchives:
      return m.campaignRegularTheForgottenAgeScenarioTheCityOfArchives();
    case EncounterSet.TheDepthsOfYoth:
      return m.campaignRegularTheForgottenAgeScenarioTheDepthsOfYoth();
    case EncounterSet.ThreadsOfFate:
      return m.campaignRegularTheForgottenAgeScenarioThreadsOfFate();
    case EncounterSet.DeadlyTraps:
      return m.campaignRegularTheForgottenAgeEncounterDeadlyTraps();
    case EncounterSet.TurnBackTime:
      return m.campaignRegularTheForgottenAgeScenarioTurnBackTime();
    case EncounterSet.YigsVenom:
      return m.campaignRegularTheForgottenAgeEncounterYigsVenom();
    case EncounterSet.TheUntamedWilds:
      return m.campaignRegularTheForgottenAgeScenarioTheUntamedWild();

    // The Innsmouth Conspiracy
    case EncounterSet.ALightInTheFog:
      return m.campaignRegularTheInnsmouthConspiracyScenarioALightInTheFog();
    case EncounterSet.AgentsOfDagon:
      return m.campaignRegularTheInnsmouthConspiracyEncounterAgentsOfDagon();
    case EncounterSet.AgentsOfHydra:
      return m.campaignRegularTheInnsmouthConspiracyEncounterAgentsOfHydra();
    case EncounterSet.CreaturesOfTheDeep:
      return m.campaignRegularTheInnsmouthConspiracyEncounterCreaturesOfTheDeep();
    case EncounterSet.DevilReef:
      return m.campaignRegularTheInnsmouthConspiracyScenarioDevilReef();
    case EncounterSet.FloodedCaverns:
      return m.campaignRegularTheInnsmouthConspiracyEncounterFloodedCaverns();
    case EncounterSet.FogOverInnsmouth:
      return m.campaignRegularTheInnsmouthConspiracyEncounterFogOverInnsmouth();
    case EncounterSet.HorrorInHighGear:
      return m.campaignRegularTheInnsmouthConspiracyScenarioHorrorInHighGear();
    case EncounterSet.InTooDeep:
      return m.campaignRegularTheInnsmouthConspiracyScenarioInTooDeep();
    case EncounterSet.IntoTheMaelstrom:
      return m.campaignRegularTheInnsmouthConspiracyScenarioIntoTheMaelstrom();
    case EncounterSet.Malfunction:
      return m.campaignRegularTheInnsmouthConspiracyEncounterMalfunction();
    case EncounterSet.RisingTide:
      return m.campaignRegularTheInnsmouthConspiracyEncounterRisingTide();
    case EncounterSet.ShatteredMemories:
      return m.campaignRegularTheInnsmouthConspiracyEncounterShatteredMemories();
    case EncounterSet.Syzygy:
      return m.campaignRegularTheInnsmouthConspiracyEncounterSyzygy();
    case EncounterSet.TheLairOfDagon:
      return m.campaignRegularTheInnsmouthConspiracyScenarioTheLairOfDagon();
    case EncounterSet.TheLocals:
      return m.campaignRegularTheInnsmouthConspiracyEncounterTheLocals();
    case EncounterSet.ThePitOfDespair:
      return m.campaignRegularTheInnsmouthConspiracyScenarioThePitOfDespair();
    case EncounterSet.TheVanishingOfElinaHarper:
      return m.campaignRegularTheInnsmouthConspiracyScenarioTheVanishingOfElinaHarper();

    // The Scarlet Keys
    case EncounterSet.AgentsOfTheOutside:
      return m.campaignRegularTheScarletKeysEncounterAgentsOfTheOutside();
    case EncounterSet.AgentsOfYuggoth:
      return m.campaignRegularTheScarletKeysEncounterAgentsOfYuggoth();
    case EncounterSet.BeyondTheBeyond:
      return m.campaignRegularTheScarletKeysEncounterBeyondTheBeyond();
    case EncounterSet.CleanupCrew:
      return m.campaignRegularTheScarletKeysEncounterCleanupCrew();
    case EncounterSet.CongressOfTheKeys:
      return m.campaignRegularTheScarletKeysScenarioCongressOfTheKeys();
    case EncounterSet.CrimsonConspiracy:
      return m.campaignRegularTheScarletKeysEncounterCrimsonConspiracy();
    case EncounterSet.DancingMad:
      return m.campaignRegularTheScarletKeysScenarioDancingMad();
    case EncounterSet.DarkVeiling:
      return m.campaignRegularTheScarletKeysEncounterDarkVeiling();
    case EncounterSet.DeadHeat:
      return m.campaignRegularTheScarletKeysScenarioDeadHeat();
    case EncounterSet.DealingsInTheDark:
      return m.campaignRegularTheScarletKeysScenarioDealingsInTheDark();
    case EncounterSet.DogsOfWar:
      return m.campaignRegularTheScarletKeysScenarioDogsOfWar();
    case EncounterSet.Globetrotting:
      return m.campaignRegularTheScarletKeysEncounterGlobetrotting();
    case EncounterSet.MysteriesAbound:
      return m.campaignRegularTheScarletKeysEncounterMysteriesAbound();
    case EncounterSet.OnThinIce:
      return m.campaignRegularTheScarletKeysScenarioOnThinIce();
    case EncounterSet.Outsiders:
      return m.campaignRegularTheScarletKeysEncounterOutsiders();
    case EncounterSet.RedCoterie:
      return m.campaignRegularTheScarletKeysEncounterRedCoterie();
    case EncounterSet.RiddlesAndRain:
      return m.campaignRegularTheScarletKeysScenarioRiddlesAndRain();
    case EncounterSet.SanguineShadows:
      return m.campaignRegularTheScarletKeysScenarioSanguineShadows();
    case EncounterSet.ScarletSorcery:
      return m.campaignRegularTheScarletKeysEncounterScarletSorcery();
    case EncounterSet.SecretWar:
      return m.campaignRegularTheScarletKeysEncounterSecretWar();
    case EncounterSet.ShadesOfSuffering:
      return m.campaignRegularTheScarletKeysScenarioShadesOfSuffering();
    case EncounterSet.ShadowOfADoubt:
      return m.campaignRegularTheScarletKeysEncounterShadowOfADoubt();
    case EncounterSet.SpatialAnomaly:
      return m.campaignRegularTheScarletKeysEncounterSpatialAnomaly();
    case EncounterSet.SpreadingCorruption:
      return m.campaignRegularTheScarletKeysEncounterSpreadingCorruption();
    case EncounterSet.StrangeHappenings:
      return m.campaignRegularTheScarletKeysEncounterStrangeHappenings();
    case EncounterSet.WithoutATrace:
      return m.campaignRegularTheScarletKeysScenarioWithoutATrace();

    // Return to The Dunwich Legacy
    case EncounterSet.BeyondTheThreshold:
      return m.campaignReturnToTheDunwichLegacyEncounterBeyondTheThreshold();
    case EncounterSet.CreepingCold:
      return m.campaignReturnToTheDunwichLegacyEncounterCreepingCold();
    case EncounterSet.ErraticFear:
      return m.campaignReturnToTheDunwichLegacyEncounterErraticFear();
    case EncounterSet.ResurgentEvils:
      return m.campaignReturnToTheDunwichLegacyEncounterResurgentEvils();
    case EncounterSet.ReturnToBloodOnTheAltar:
      return m.campaignReturnToTheDunwichLegacyScenarioReturnToBloodOnTheAltar();
    case EncounterSet.ReturnToExtracurricularActivity:
      return m.campaignReturnToTheDunwichLegacyScenarioReturnToExtracurricularActivity();
    case EncounterSet.ReturnToLostInTimeAndSpace:
      return m.campaignReturnToTheDunwichLegacyScenarioReturnToLostInTimeAndSpace();
    case EncounterSet.ReturnToTheEssexCountyExpress:
      return m.campaignReturnToTheDunwichLegacyScenarioReturnToTheEssexCountyExpress();
    case EncounterSet.ReturnToTheHouseAlwaysWins:
      return m.campaignReturnToTheDunwichLegacyScenarioReturnToTheHouseAlwaysWins();
    case EncounterSet.ReturnToTheMiskatonicMuseum:
      return m.campaignReturnToTheDunwichLegacyScenarioReturnToTheMiskatonicMuseum();
    case EncounterSet.ReturnToUndimensionedAndUnseen:
      return m.campaignReturnToTheDunwichLegacyScenarioReturnToUndimensionedAndUnseen();
    case EncounterSet.ReturnToWhereDoomAwaits:
      return m.campaignReturnToTheDunwichLegacyScenarioReturnToWhereDoomAwaits();
    case EncounterSet.SecretDoors:
      return m.campaignReturnToTheDunwichLegacyEncounterSecretDoors();
    case EncounterSet.YogSothothsEmissaries:
      return m.campaignReturnToTheDunwichLegacyEncounterYogSothothsEmissaries();

    // Return to The Night of the Zealot
    case EncounterSet.GhoulsOfUmordhoth:
      return m.campaignReturnToNightOfTheZealotEncounterGhoulsOfUmrdhoth();
    case EncounterSet.ReturnToCultOfUmordhoth:
      return m.campaignReturnToNightOfTheZealotEncounterCultOfUmrdhothNew();
    case EncounterSet.ReturnToTheDevourerBelow:
      return m.campaignReturnToNightOfTheZealotScenarioReturnToTheDevourerBelow();
    case EncounterSet.ReturnToTheGathering:
      return m.campaignReturnToNightOfTheZealotScenarioReturnToTheGathering();
    case EncounterSet.ReturnToTheMidnightMasks:
      return m.campaignReturnToNightOfTheZealotScenarioReturnToTheMidnightMasks();
    case EncounterSet.TheDevourersCult:
      return m.campaignReturnToNightOfTheZealotEncounterTheDevourersCult();

    // Return to The Path to Carcosa
    case EncounterSet.DecayingReality:
      return m.campaignReturnToThePathToCarcosaEncounterDecayingReality();
    case EncounterSet.DelusoryEvils:
      return m.campaignReturnToThePathToCarcosaEncounterDelusoryEvils();
    case EncounterSet.HastursEnvoys:
      return m.campaignReturnToThePathToCarcosaEncounterHastursEnvoys();
    case EncounterSet.MaddeningDelusions:
      return m.campaignReturnToThePathToCarcosaEncounterMaddeningDelusions();
    case EncounterSet.NeuroticFear:
      return m.campaignReturnToThePathToCarcosaEncounterNeuroticFear();
    case EncounterSet.ReturnToAPhantomOfTruth:
      return m.campaignReturnToThePathToCarcosaScenarioReturnToAPhantomOfTruth();
    case EncounterSet.ReturnToBlackStarsRise:
      return m.campaignReturnToThePathToCarcosaScenarioReturnToBlackStarsRise();
    case EncounterSet.ReturnToCurtainCall:
      return m.campaignReturnToThePathToCarcosaScenarioReturnToCurtainCall();
    case EncounterSet.ReturnToDimCarcosa:
      return m.campaignReturnToThePathToCarcosaScenarioReturnToDimCarcosa();
    case EncounterSet.ReturnToEchoesOfThePast:
      return m.campaignReturnToThePathToCarcosaScenarioReturnToEchoesOfThePast();
    case EncounterSet.ReturnToTheLastKing:
      return m.campaignReturnToThePathToCarcosaScenarioReturnToTheLastKing();
    case EncounterSet.ReturnToThePallidMask:
      return m.campaignReturnToThePathToCarcosaScenarioReturnToThePallidMask();
    case EncounterSet.ReturnToTheUnspeakableOath:
      return m.campaignReturnToThePathToCarcosaScenarioReturnToTheUnspeakableOath();

    // Return to The Circle Undone
    case EncounterSet.BloodthirstySpirits:
      return m.campaignReturnToTheCircleUndoneEncounterBloodthirstySpirits();
    case EncounterSet.ChillingMists:
      return m.campaignReturnToTheCircleUndoneEncounterChillingMists();
    case EncounterSet.CityOfTheDamned:
      return m.campaignReturnToTheCircleUndoneEncounterCityOfTheDamned();
    case EncounterSet.Hexcraft:
      return m.campaignReturnToTheCircleUndoneEncounterHexcraft();
    case EncounterSet.ImpendingEvils:
      return m.campaignReturnToTheCircleUndoneEncounterImpendingEvils();
    case EncounterSet.ReturnToAtDeathsDoorstep:
      return m.campaignReturnToTheCircleUndoneScenarioReturnToAtDeathsDoorstep();
    case EncounterSet.ReturnToBeforeTheBlackThrone:
      return m.campaignReturnToTheCircleUndoneScenarioReturnToBeforeTheBlackThrone();
    case EncounterSet.ReturnToDisappearanceAtTheTwilightEstate:
      return m.campaignReturnToTheCircleUndoneScenarioReturnToDisappearanceAtTheTwilightEstate();
    case EncounterSet.ReturnToForTheGreaterGood:
      return m.campaignReturnToTheCircleUndoneScenarioReturnToForTheGreaterGood();
    case EncounterSet.ReturnToInTheClutchesOfChaos:
      return m.campaignReturnToTheCircleUndoneScenarioReturnToInTheClutchesOfChaos();
    case EncounterSet.ReturnToTheSecretName:
      return m.campaignReturnToTheCircleUndoneScenarioReturnToTheSecretName();
    case EncounterSet.ReturnToTheWagesOfSin:
      return m.campaignReturnToTheCircleUndoneScenarioReturnToTheWagesOfSin();
    case EncounterSet.ReturnToTheWitchingHour:
      return m.campaignReturnToTheCircleUndoneScenarioReturnToTheWitchingHour();
    case EncounterSet.ReturnToUnionAndDisillusion:
      return m.campaignReturnToTheCircleUndoneScenarioReturnToUnionAndDisillusion();
    case EncounterSet.UnspeakableFate:
      return m.campaignReturnToTheCircleUndoneEncounterUnspeakableFate();
    case EncounterSet.UnstableRealm:
      return m.campaignReturnToTheCircleUndoneEncounterUnstableRealm();

    // Return to The Forgotten Age
    case EncounterSet.CultOfPnakotus:
      return m.campaignReturnToTheForgottenAgeEncounterCultOfPnakotus();
    case EncounterSet.DoomedExpedition:
      return m.campaignReturnToTheForgottenAgeEncounterDoomedExpedition();
    case EncounterSet.ReturnToKnyan:
      return m.campaignReturnToTheForgottenAgeScenarioReturnToKnyan();
    case EncounterSet.ReturnToPillarsOfJudgment:
      return m.campaignReturnToTheForgottenAgeScenarioReturnToPillarsOfJudgement();
    case EncounterSet.ReturnToShatteredAeons:
      return m.campaignReturnToTheForgottenAgeScenarioReturnToShatteredAeons();
    case EncounterSet.ReturnToTheBoundaryBeyond:
      return m.campaignReturnToTheForgottenAgeScenarioReturnToTheBoundaryBeyond();
    case EncounterSet.ReturnToTheCityOfArchives:
      return m.campaignReturnToTheForgottenAgeScenarioReturnToTheCityOfArchives();
    case EncounterSet.ReturnToTheDepthsOfYoth:
      return m.campaignReturnToTheForgottenAgeScenarioReturnToTheDepthsOfYoth();
    case EncounterSet.ReturnToTheDoomOfEztli:
      return m.campaignReturnToTheForgottenAgeScenarioReturnToTheDoomOfEztli();
    case EncounterSet.ReturnToTheRainforest:
      return m.campaignReturnToTheForgottenAgeEncounterReturnToTheRainforest();
    case EncounterSet.ReturnToTheUntamedWilds:
      return m.campaignReturnToTheForgottenAgeScenarioReturnToTheUntamedWild();
    case EncounterSet.ReturnToThreadsOfFate:
      return m.campaignReturnToTheForgottenAgeScenarioReturnToThreadsOfFate();
    case EncounterSet.ReturnToTurnBackTime:
      return m.campaignReturnToTheForgottenAgeScenarioReturnToTurnBackTime();
    case EncounterSet.TemporalHunters:
      return m.campaignReturnToTheForgottenAgeEncounterTemporalHunters();
    case EncounterSet.VenomousHate:
      return m.campaignReturnToTheForgottenAgeEncounterVenomousHate();

    // Standalone Scenarios
    // The Blob That Ate Everything ELSE
    case EncounterSet.TheBlobThatAteEverythingElse:
      return m.standaloneScenarioTheBlobThatAteEverythingElseTheBlobThatAteEverythingElse();
    case EncounterSet.MigoIncursionII:
      return m.standaloneScenarioTheBlobThatAteEverythingElseMiGoIncursionII();

    // The Blob That Ate Everything (original)
    case EncounterSet.TheBlobThatAteEverything:
      return m.standaloneScenarioNameTheBlobThatAteEverything();
    case EncounterSet.TheBlobThatAteEverythingEpicMultiplayer:
      return m.standaloneScenarioTheBlobThatAteEverythingEpicMultiplayer();
    case EncounterSet.TheBlobThatAteEverythingSingleGroup:
      return m.standaloneScenarioTheBlobThatAteEverythingSingleGroup();
    case EncounterSet.MigoIncursion:
      return m.standaloneScenarioTheBlobThatAteEverythingMiGoIncursion();

    // Carnevale of Horrors
    case EncounterSet.CarnevaleOfHorrors:
      return m.standaloneScenarioNameCarnevaleOfHorrors();

    // Curse of the Rougarou
    case EncounterSet.TheBayou:
      return m.standaloneScenarioCurseOfTheRougarouTheBayou();
    case EncounterSet.CurseOfTheRougarou:
      return m.standaloneScenarioNameCurseOfTheRougarou();

    // Film Fatale
    case EncounterSet.AbominableContessa:
      return m.standaloneScenarioFilmFataleAbominableContessa();
    case EncounterSet.CosmicJourney:
      return m.standaloneScenarioFilmFataleCosmicJourney();
    case EncounterSet.FilmFatale:
      return m.standaloneScenarioFilmFataleFilmFatale();
    case EncounterSet.ForgottenIsland:
      return m.standaloneScenarioFilmFataleForgottenIsland();

    // Fortune and Folly
    case EncounterSet.FortuneAndFolly:
      return m.standaloneScenarioFortuneAndFollyFortuneAndFolly();
    case EncounterSet.FortunesChosen:
      return m.standaloneScenarioFortuneAndFollyFortunesChosen();
    case EncounterSet.PlanInShambles:
      return m.standaloneScenarioFortuneAndFollyPlanInShambles();

    // Guardians of the Abyss
    case EncounterSet.AbyssalGifts:
      return m.standaloneScenarioGuardiansOfTheAbyssAbyssalGifts();
    case EncounterSet.AbyssalTribute:
      return m.standaloneScenarioGuardiansOfTheAbyssAbyssalTribute();
    case EncounterSet.BrotherhoodOfTheBeast:
      return m.standaloneScenarioGuardiansOfTheAbyssBrotherhoodOfTheBeast();
    case EncounterSet.SandsOfEgypt:
      return m.standaloneScenarioGuardiansOfTheAbyssSandsOfEgypt();
    case EncounterSet.TheEternalSlumber:
      return m.standaloneScenarioGuardiansOfTheAbyssTheEternalSlumber();
    case EncounterSet.TheNightsUsurper:
      return m.standaloneScenarioGuardiansOfTheAbyssTheNightsUsurper();

    // Murder at the Excelsior Hotel
    case EncounterSet.AlienInterference:
      return m.standaloneScenarioMurderAtTheExcelsiorHotelAlienInterference();
    case EncounterSet.DarkRituals:
      return m.standaloneScenarioMurderAtTheExcelsiorHotelDarkRituals();
    case EncounterSet.ExcelsiorManagement:
      return m.standaloneScenarioMurderAtTheExcelsiorHotelExcelsiorManagement();
    case EncounterSet.MurderAtTheExcelsiorHotel:
      return m.standaloneScenarioNameMurderAtTheExcelsiorHotel();
    case EncounterSet.SinsOfThePast:
      return m.standaloneScenarioMurderAtTheExcelsiorHotelSinsOfThePast();
    case EncounterSet.VileExperiments:
      return m.standaloneScenarioMurderAtTheExcelsiorHotelVileExperiments();

    // The Labyrinths of Lunacy
    case EncounterSet.TheLabyrinthsOfLunacyEpicMultiplayer:
      return m.standaloneScenarioTheLabyrinthsOfLunacyEpicMultiplayer();
    case EncounterSet.TheLabyrinthsOfLunacy:
      return m.standaloneScenarioNameTheLabyrinthsOfLunacy();
    case EncounterSet.TheLabyrinthsOfLunacySingleGroup:
      return m.standaloneScenarioTheLabyrinthsOfLunacySingleGroup();

    // Machinations Through Time
    case EncounterSet.MachinationsThroughTime:
      return m.standaloneScenarioNameMachinationsThroughTime();
    case EncounterSet.MachinationsThroughTimeEpicMultiplayer:
      return m.standaloneScenarioMachinationsThroughTimeEpicMultiplayer();
    case EncounterSet.MachinationsThroughTimeSingleGroup:
      return m.standaloneScenarioMachinationsThroughTimeSingleGroup();

    // The Midwinter Gala
    case EncounterSet.TheMidwinterGala:
      return m.standaloneScenarioTheMidwinterGalaTheMidwinterGala();

    // War of the Outer Gods
    case EncounterSet.ChildrenOfParadise:
      return m.standaloneScenarioWarOfTheOuterGodsChildrenOfParadise();
    case EncounterSet.DeathOfStars:
      return m.standaloneScenarioWarOfTheOuterGodsDeathOfStars();
    case EncounterSet.SwarmOfAssimilation:
      return m.standaloneScenarioWarOfTheOuterGodsSwarmOfAssimilation();
    case EncounterSet.WarOfTheOuterGods:
      return m.standaloneScenarioNameWarOfTheOuterGods();

    default: {
      const _exhaustive: never = encounterSet;
      throw new Error(`Unhandled encounter set: ${_exhaustive}`);
    }
  }
}
