import { Product, productReturnTo, productCoreSets } from './product.js';
import { Campaign, StandaloneScenario } from './campaign.js';

export enum EncounterSet {
  // Core Set
  AgentsOfCthulhu = 'agents_of_cthulhu',
  AgentsOfHastur = 'agents_of_hastur',
  AgentsOfShubniggurath = 'agents_of_shub',
  AgentsOfYogsothoth = 'agents_of_yog',
  AncientEvils = 'ancient_evils',
  ChillingCold = 'chilling_cold',
  CultOfUmrdhoth = 'cultists',
  DarkCult = 'pentagram',
  Ghouls = 'ghouls',
  LockedDoors = 'locked_doors',
  Nightgaunts = 'nightgaunts',
  Rats = 'rats',
  StrikingFear = 'striking_fear',
  TheDevourerBelow = 'tentacles',
  TheGathering = 'torch',
  TheMidnightMasks = 'arkham',

  // The Dunwich Legacy
  ArmitagesFate = 'armitages_fate',
  BadLuck = 'bad_luck',
  BeastThralls = 'beast_thralls',
  BishopsThralls = 'bishops_thralls',
  BloodOnTheAltar = 'blood_on_the_altar',
  Dunwich = 'dunwich',
  TheEssexCountyExpress = 'essex_county_express',
  ExtracurricularActivity = 'extracurricular_activity',
  HideousAbominations = 'hideous_abominations',
  LostInTimeAndSpace = 'lost_in_time_and_space',
  NaomisCrew = 'naomis_crew',
  Sorcery = 'sorcery',
  TheBeyond = 'the_beyond',
  TheHouseAlwaysWins = 'the_house_always_wins',
  TheMiskatonicMuseum = 'the_miskatonic_museum',
  UndimensionedAndUnseen = 'undimensioned_and_unseen',
  WhereDoomAwaits = 'where_doom_awaits',
  Whippoorwills = 'whippoorwills',

  // Edge of the Earth
  AgentsOfTheUnknown = 'agents_of_the_unknown',
  CityOfTheElderThings = 'city_of_the_elder_things',
  CreaturesInTheIce = 'creatures_in_the_ice',
  DeadlyWeather = 'deadly_weather',
  ElderThings = 'elder_things',
  ExpeditionTeam = 'expedition_team',
  FatalMirage = 'fatal_mirage',
  HazardsOfAntarctica = 'hazards_of_antarctica',
  IceAndDeath = 'ice_and_death',
  LeftBehind = 'left_behind',
  LostInTheNight = 'lost_in_the_night',
  MemorialsOfTheLost = 'memorials_of_the_lost',
  Miasma = 'miasma',
  NamelessHorrors = 'nameless_horrors',
  Penguins = 'penguins',
  SeepingNightmares = 'seeping_nightmares',
  Shoggoths = 'shoggoths',
  SilenceAndMystery = 'silence_and_mystery',
  StirringInTheDeep = 'stirring_in_the_deep',
  Tekelili = 'tekelili',
  TheCrash = 'the_crash',
  TheGreatSeal = 'the_great_seal',
  TheHeartOfMadness = 'the_heart_of_madness',
  ToTheForbiddenPeaks = 'to_the_forbidden_peaks',

  // The Feast of Hemlock Vale
  AgentsOfTheColour = 'agents_of_the_colour',
  Blight = 'blight',
  DayOfRain = 'day_of_rain',
  DayOfRest = 'day_of_rest',
  DayOfTheFeast = 'day_of_the_feast',
  FateOfTheVale = 'fate_of_the_vale',
  Fire = 'fire',
  Heirlooms = 'heirlooms',
  HemlockHouse = 'hemlock_house',
  HorrorsInTheRock = 'horrors_in_the_rock',
  Mutations = 'mutations',
  Myconids = 'myconids',
  Refractions = 'refractions',
  Residents = 'residents',
  TheFinalDay = 'the_final_day',
  TheFirstDay = 'the_first_day',
  TheForest = 'the_forest',
  TheLongestNight = 'the_longest_night',
  TheLostSister = 'the_lost_sister',
  TheSecondDay = 'the_second_day',
  TheSilentHeath = 'the_silent_heath',
  TheThingInTheDepths = 'the_thing_in_the_depths',
  TheTwistedHollow = 'the_twisted_hollow',
  TheVale = 'the_vale',
  Transfiguration = 'transfiguration',
  WrittenInRock = 'written_in_rock',

  // Parallel
  AllOrNothing = 'all_or_nothing',
  BadBlood = 'bad_blood',
  ByTheBook = 'by_the_book',
  LaidToRest = 'laid_to_rest',
  ReadOrDie = 'read_or_die',
  RedTideRising = 'red_tide_rising',
  RelicsOfThePast = 'relics_of_the_past',

  // The Path to Carcosa
  APhantomOfTruth = 'a_phantom_of_truth',
  BlackStarsRise = 'black_stars_rise',
  Byakhee = 'byakhee',
  CultOfTheYellowSign = 'cult_of_the_yellow_sign',
  CurtainCall = 'curtain_call',
  DecayAndFilth = 'decay',
  Delusions = 'delusions',
  DimCarcosa = 'dim_carcosa',
  EchoesOfThePast = 'echoes_of_the_past',
  EvilPortents = 'evil_portents',
  TheFloodBelow = 'flood',
  HastursGift = 'hasturs_gift',
  Hauntings = 'hauntings',
  InhabitantsOfCarcosa = 'inhabitants_of_carcosa',
  TheStranger = 'stranger',
  TheLastKing = 'the_last_king',
  ThePallidMask = 'the_pallid_mask',
  TheUnspeakableOath = 'the_unspeakable_oath',
  TheVortexAbove = 'vortex',

  // The Circle Undone
  AgentsOfAzathoth = 'agents_of_azathoth',
  AnettesCoven = 'anettes_coven',
  AtDeathsDoorstep = 'at_deaths_doorstep',
  BeforeTheBlackThrone = 'before_the_black_throne',
  CityOfSins = 'city_of_sins',
  DisappearanceAtTheTwilightEstate = 'disappearance_at_the_twilight_estate',
  ForTheGreaterGood = 'for_the_greater_good',
  InTheClutchesOfChaos = 'in_the_clutches_of_chaos',
  InexorableFate = 'inexorable_fate',
  MusicOfTheDamned = 'music_of_the_damned',
  RealmOfDeath = 'realm_of_death',
  SecretsOfTheUniverse = 'secrets_of_the_universe',
  SilverTwilightLodge = 'silver_twilight_lodge',
  SpectralPredators = 'spectral_predators',
  TheSecretName = 'the_secret_name',
  TheWagesOfSin = 'the_wages_of_sin',
  TheWatcher = 'the_watcher',
  TheWitchingHour = 'the_witching_hour',
  TrappedSpirits = 'trapped_spirits',
  UnionAndDisillusion = 'union_and_disillusion',
  Witchcraft = 'witchcraft',

  // The Drowned City
  AlienMachinery = 'alien_machinery',
  CosmicLegacy = 'cosmic_legacy',
  CourtOfTheAncients = 'court_of_the_ancients',
  DeepOnes = 'deep_ones',
  Domination = 'domination',
  Dreams = 'dreams',
  ElderMist = 'elder_mist',
  ObsidianCanyons = 'obsidian_canyons',
  OneLastJob = 'one_last_job',
  Pilgrims = 'pilgrims',
  Rlyeh = 'rlyeh',
  SepulchreOfTheSleeper = 'sepulchre_of_the_sleeper',
  StarSpawn = 'star_spawn',
  Stowaways = 'stowaways',
  Tasks = 'tasks',
  TdcExpedition = 'tdc_expedition',
  TdcFlood = 'tdc_flood',
  TheApiary = 'the_apiary',
  TheDoomOfArkhamPart1 = 'the_doom_of_arkham_part_1',
  TheDoomOfArkhamPart2 = 'the_doom_of_arkham_part_2',
  TheDrownedQuarter = 'the_drowned_quarter',
  TheGrandVault = 'the_grand_vault',
  TheInescapable = 'the_inescapable',
  TheWesternWall = 'the_western_wall',
  UnderseaCreatures = 'undersea_creatures',

  // The Dream-Eaters
  AgentsOfAtlachNacha = 'agents_of_atlach_nacha',
  AgentsOfNyarlathotep = 'agents_of_nyarlathotep',
  AThousandShapesOfHorror = 'a_thousand_shapes_of_horror',
  BeyondTheGatesOfSleep = 'beyond_the_gates_of_sleep',
  Corsairs = 'corsairs',
  CreaturesOfTheUnderworld = 'creatures_of_the_underworld',
  DarkSideOfTheMoon = 'dark_side_of_the_moon',
  DescentIntoThePitch = 'descent_into_the_pitch',
  DreamersCurse = 'dreamers_curse',
  Dreamlands = 'dreamlands',
  MergingRealities = 'merging_realities',
  PointOfNoReturn = 'point_of_no_return',
  Spiders = 'spiders',
  TerrorOfTheVale = 'terror_of_the_vale',
  TheSearchForKadath = 'the_search_for_kadath',
  WakingNightmare = 'waking_nightmare',
  WeaverOfTheCosmos = 'weaver_of_the_cosmos',
  WhereTheGodsDwell = 'where_the_gods_dwell',
  WhispersOfHypnos = 'whispers_of_hypnos',
  Zoogs = 'zoogs',

  // The Forgotten Age
  AgentsOfYig = 'agents_of_yig',
  Expedition = 'expedition',
  TheDoomOfEztli = 'eztli',
  TemporalFlux = 'flux',
  GuardiansOfTime = 'guardians_of_time',
  HeartOfTheElders = 'heart_of_the_elders',
  Knyan = 'knyan',
  PillarsOfJudgment = 'pillars_of_judgment',
  PnakoticBrotherhood = 'pnakotic_brotherhood',
  Poison = 'poison',
  Rainforest = 'rainforest',
  ForgottenRuins = 'ruins',
  Serpents = 'serpents',
  ShatteredAeons = 'shattered_aeons',
  TheBoundaryBeyond = 'the_boundary_beyond',
  TheCityOfArchives = 'the_city_of_archives',
  TheDepthsOfYoth = 'the_depths_of_yoth',
  ThreadsOfFate = 'threads_of_fate',
  DeadlyTraps = 'traps',
  TurnBackTime = 'turn_back_time',
  YigsVenom = 'venom',
  TheUntamedWilds = 'wilds',

  // The Innsmouth Conspiracy
  ALightInTheFog = 'a_light_in_the_fog',
  AgentsOfDagon = 'agents_of_dagon',
  AgentsOfHydra = 'agents_of_hydra',
  CreaturesOfTheDeep = 'creatures_of_the_deep',
  DevilReef = 'devil_reef',
  FloodedCaverns = 'flooded_caverns',
  FogOverInnsmouth = 'fog_over_innsmouth',
  HorrorInHighGear = 'horror_in_high_gear',
  InTooDeep = 'in_too_deep',
  IntoTheMaelstrom = 'into_the_maelstrom',
  Malfunction = 'malfunction',
  RisingTide = 'rising_tide',
  ShatteredMemories = 'shattered_memories',
  Syzygy = 'syzygy',
  TheLairOfDagon = 'the_lair_of_dagon',
  TheLocals = 'the_locals',
  ThePitOfDespair = 'the_pit_of_despair',
  TheVanishingOfElinaHarper = 'the_vanishing_of_elina_harper',

  // The Scarlet Keys
  AgentsOfTheOutside = 'agents_of_the_outside',
  AgentsOfYuggoth = 'agents_of_yuggoth',
  BeyondTheBeyond = 'beyond_the_beyond',
  CleanupCrew = 'cleanup_crew',
  CongressOfTheKeys = 'congress_of_the_keys',
  CrimsonConspiracy = 'crimson_conspiracy',
  DancingMad = 'dancing_mad',
  DarkVeiling = 'dark_veiling',
  DeadHeat = 'dead_heat',
  DealingsInTheDark = 'dealings_in_the_dark',
  DogsOfWar = 'dogs_of_war',
  Globetrotting = 'globetrotting',
  MysteriesAbound = 'mysteries_abound',
  OnThinIce = 'on_thin_ice',
  Outsiders = 'outsiders',
  RedCoterie = 'red_coterie',
  RiddlesAndRain = 'riddles_and_rain',
  SanguineShadows = 'sanguine_shadows',
  ScarletSorcery = 'scarlet_sorcery',
  SecretWar = 'secret_war',
  ShadesOfSuffering = 'shades_of_suffering',
  ShadowOfADoubt = 'shadow_of_a_doubt',
  SpatialAnomaly = 'spatial_anomaly',
  SpreadingCorruption = 'spreading_corruption',
  StrangeHappenings = 'strange_happenings',
  WithoutATrace = 'without_a_trace',

  // Return to... Cycles
  // Return to The Dunwich Legacy
  BeyondTheThreshold = 'beyond_the_threshold',
  CreepingCold = 'creeping_cold',
  ErraticFear = 'erratic_fear',
  ResurgentEvils = 'resurgent_evils',
  ReturnToBloodOnTheAltar = 'return_to_blood_on_the_altar',
  ReturnToExtracurricularActivity = 'return_to_extracurricular_activities',
  ReturnToLostInTimeAndSpace = 'return_to_lost_in_time_and_space',
  ReturnToTheEssexCountyExpress = 'return_to_the_essex_county_express',
  ReturnToTheHouseAlwaysWins = 'return_to_the_house_always_wins',
  ReturnToTheMiskatonicMuseum = 'return_to_the_miskatonic_museum',
  ReturnToUndimensionedAndUnseen = 'return_to_undimensioned_and_unseen',
  ReturnToWhereDoomAwaits = 'return_to_where_doom_awaits',
  SecretDoors = 'secret_doors',
  YogSothothsEmissaries = 'yog_sothoths_emissaries',

  // Return to The Night of the Zealot
  GhoulsOfUmordhoth = 'ghouls_of_umôrdhoth',
  ReturnToCultOfUmordhoth = 'return_cult',
  ReturnToTheDevourerBelow = 'return_to_the_devourer_below',
  ReturnToTheGathering = 'return_to_the_gathering',
  ReturnToTheMidnightMasks = 'return_to_the_midnight_masks',
  TheDevourersCult = 'the_devourers_cult',

  // Return to The Path to Carcosa
  DecayingReality = 'decaying_reality',
  DelusoryEvils = 'delusory_evils',
  HastursEnvoys = 'hasturs_envoys',
  MaddeningDelusions = 'maddening_delusions',
  NeuroticFear = 'neurotic_fear',
  ReturnToAPhantomOfTruth = 'return_to_a_phantom_of_truth',
  ReturnToBlackStarsRise = 'return_to_black_stars_rise',
  ReturnToCurtainCall = 'return_to_curtain_call',
  ReturnToDimCarcosa = 'return_to_dim_carcosa',
  ReturnToEchoesOfThePast = 'return_to_echoes_of_the_past',
  ReturnToTheLastKing = 'return_to_the_last_king',
  ReturnToThePallidMask = 'return_to_the_pallid_mask',
  ReturnToTheUnspeakableOath = 'return_to_the_unspeakable_oath',

  // Return to The Circle Undone
  BloodthirstySpirits = 'bloodthirsty_spirits',
  ChillingMists = 'chilling_mists',
  CityOfTheDamned = 'city_of_the_damned',
  Hexcraft = 'hexcraft',
  ImpendingEvils = 'impending_evils',
  ReturnToAtDeathsDoorstep = 'return_to_at_deaths_doorstep',
  ReturnToBeforeTheBlackThrone = 'return_to_before_the_black_throne',
  ReturnToDisappearanceAtTheTwilightEstate = 'return_to_disappearance_at_the_twilight_estate',
  ReturnToForTheGreaterGood = 'return_to_for_the_greater_good',
  ReturnToInTheClutchesOfChaos = 'return_to_in_the_clutches_of_chaos',
  ReturnToTheSecretName = 'return_to_the_secret_name',
  ReturnToTheWagesOfSin = 'return_to_the_wages_of_sin',
  ReturnToTheWitchingHour = 'return_to_the_witching_hour',
  ReturnToUnionAndDisillusion = 'return_to_union_and_disillusion',
  UnspeakableFate = 'unspeakable_fate',
  UnstableRealm = 'unstable_realm',

  // Return to The Forgotten Age
  CultOfPnakotus = 'cult_of_pnakotus',
  DoomedExpedition = 'doomed_expedition',
  ReturnToKnyan = 'return_to_knyan',
  ReturnToPillarsOfJudgment = 'return_to_pillars_of_judgment',
  ReturnToShatteredAeons = 'return_to_shattered_aeons',
  ReturnToTheBoundaryBeyond = 'return_to_the_boundary_beyond',
  ReturnToTheCityOfArchives = 'return_to_the_city_of_archives',
  ReturnToTheDepthsOfYoth = 'return_to_the_depths_of_yoth',
  ReturnToTheDoomOfEztli = 'return_to_the_doom_of_eztli',
  ReturnToTheRainforest = 'return_to_the_rainforest',
  ReturnToTheUntamedWilds = 'return_to_the_untamed_wilds',
  ReturnToThreadsOfFate = 'return_to_threads_of_fate',
  ReturnToTurnBackTime = 'return_to_turn_back_time',
  TemporalHunters = 'temporal_hunters',
  VenomousHate = 'venomous_hate',

  // Standalone Scenarios
  // The Blob That Ate Everything ELSE
  TheBlobThatAteEverythingElse = 'blob_that_ate_everything_else',
  MigoIncursionII = 'migo_incursion_2',

  // The Blob That Ate Everything
  TheBlobThatAteEverything = 'blob',
  TheBlobThatAteEverythingEpicMultiplayer = 'blob_epic_multiplayer',
  TheBlobThatAteEverythingSingleGroup = 'blob_single_group',
  MigoIncursion = 'migo_incursion',

  // Carnevale of Horrors
  CarnevaleOfHorrors = 'venice',

  // Curse of the Rougarou
  TheBayou = 'bayou',
  CurseOfTheRougarou = 'rougarou',

  // Film Fatale
  AbominableContessa = 'abominable_contessa',
  CosmicJourney = 'cosmic_journey',
  FilmFatale = 'film_fatale',
  ForgottenIsland = 'forgotten_island',

  // Fortune and Folly
  FortuneAndFolly = 'fortune_and_folly',
  FortunesChosen = 'fortunes_chosen',
  PlanInShambles = 'plan_in_shambles',

  // Guardians of the Abyss
  AbyssalGifts = 'abyssal_gifts',
  AbyssalTribute = 'abyssal_tribute',
  BrotherhoodOfTheBeast = 'brotherhood_of_the_beast',
  SandsOfEgypt = 'sands_of_egypt',
  TheEternalSlumber = 'the_eternal_slumber',
  TheNightsUsurper = 'the_nights_usurper',

  // Murder at the Excelsior Hotel
  AlienInterference = 'alien_interference',
  DarkRituals = 'dark_rituals',
  ExcelsiorManagement = 'excelsior_management',
  MurderAtTheExcelsiorHotel = 'murder_at_the_excelsior_hotel',
  SinsOfThePast = 'sins_of_the_past',
  VileExperiments = 'vile_experiments',

  // The Labyrinths of Lunacy
  TheLabyrinthsOfLunacyEpicMultiplayer = 'epic_multiplayer',
  TheLabyrinthsOfLunacy = 'in_the_labyrinths_of_lunacy',
  TheLabyrinthsOfLunacySingleGroup = 'single_group',

  // Machinations Through Time
  MachinationsThroughTime = 'machinations_through_time',
  MachinationsThroughTimeEpicMultiplayer = 'machinations_through_time_epic_multiplayer',
  MachinationsThroughTimeSingleGroup = 'machinations_through_time_single_group',

  // The Midwinter Gala
  TheMidwinterGala = 'the_midwinter_gala',

  // War of the Outer Gods
  ChildrenOfParadise = 'children_of_paradise',
  DeathOfStars = 'death_of_stars',
  SwarmOfAssimilation = 'swarm_of_assimilation',
  WarOfTheOuterGods = 'war_of_the_outer_gods',
}

/**
 * Maps Products to their associated EncounterSets.
 * Only includes products that provide campaign/encounter cards.
 */
export const productEncounterSetsMap: Partial<Record<Product, EncounterSet[]>> = {
  [Product.CoreSet]: [
    EncounterSet.AgentsOfCthulhu,
    EncounterSet.AgentsOfHastur,
    EncounterSet.AgentsOfShubniggurath,
    EncounterSet.AgentsOfYogsothoth,
    EncounterSet.AncientEvils,
    EncounterSet.CultOfUmrdhoth,
    EncounterSet.ChillingCold,
    EncounterSet.DarkCult,
    EncounterSet.LockedDoors,
    EncounterSet.Nightgaunts,
    EncounterSet.Rats,
    EncounterSet.StrikingFear,
    EncounterSet.TheDevourerBelow,
    EncounterSet.TheGathering,
    EncounterSet.TheMidnightMasks,
    EncounterSet.Ghouls,
  ],
  [Product.TheDunwichLegacyCampaignExpansion]: [
    EncounterSet.ArmitagesFate,
    EncounterSet.BadLuck,
    EncounterSet.BeastThralls,
    EncounterSet.BishopsThralls,
    EncounterSet.BloodOnTheAltar,
    EncounterSet.Dunwich,
    EncounterSet.TheEssexCountyExpress,
    EncounterSet.ExtracurricularActivity,
    EncounterSet.HideousAbominations,
    EncounterSet.LostInTimeAndSpace,
    EncounterSet.NaomisCrew,
    EncounterSet.Sorcery,
    EncounterSet.TheBeyond,
    EncounterSet.TheHouseAlwaysWins,
    EncounterSet.TheMiskatonicMuseum,
    EncounterSet.UndimensionedAndUnseen,
    EncounterSet.WhereDoomAwaits,
    EncounterSet.Whippoorwills,
  ],
  [Product.EdgeOfTheEarthCampaignExpansion]: [
    EncounterSet.AgentsOfTheUnknown,
    EncounterSet.CityOfTheElderThings,
    EncounterSet.CreaturesInTheIce,
    EncounterSet.DeadlyWeather,
    EncounterSet.ElderThings,
    EncounterSet.ExpeditionTeam,
    EncounterSet.FatalMirage,
    EncounterSet.HazardsOfAntarctica,
    EncounterSet.IceAndDeath,
    EncounterSet.LeftBehind,
    EncounterSet.LostInTheNight,
    EncounterSet.MemorialsOfTheLost,
    EncounterSet.Miasma,
    EncounterSet.NamelessHorrors,
    EncounterSet.Penguins,
    EncounterSet.SeepingNightmares,
    EncounterSet.Shoggoths,
    EncounterSet.SilenceAndMystery,
    EncounterSet.StirringInTheDeep,
    EncounterSet.Tekelili,
    EncounterSet.TheCrash,
    EncounterSet.TheGreatSeal,
    EncounterSet.TheHeartOfMadness,
    EncounterSet.ToTheForbiddenPeaks,
  ],
  [Product.TheFeastOfHemlockValeCampaignExpansion]: [
    EncounterSet.AgentsOfTheColour,
    EncounterSet.Blight,
    EncounterSet.DayOfRain,
    EncounterSet.DayOfRest,
    EncounterSet.DayOfTheFeast,
    EncounterSet.FateOfTheVale,
    EncounterSet.Fire,
    EncounterSet.Heirlooms,
    EncounterSet.HemlockHouse,
    EncounterSet.HorrorsInTheRock,
    EncounterSet.Mutations,
    EncounterSet.Myconids,
    EncounterSet.Refractions,
    EncounterSet.Residents,
    EncounterSet.TheFinalDay,
    EncounterSet.TheFirstDay,
    EncounterSet.TheForest,
    EncounterSet.TheLongestNight,
    EncounterSet.TheLostSister,
    EncounterSet.TheSecondDay,
    EncounterSet.TheSilentHeath,
    EncounterSet.TheThingInTheDepths,
    EncounterSet.TheTwistedHollow,
    EncounterSet.TheVale,
    EncounterSet.Transfiguration,
    EncounterSet.WrittenInRock,
  ],
  [Product.ParallelInvestigators]: [
    EncounterSet.AllOrNothing,
    EncounterSet.BadBlood,
    EncounterSet.ByTheBook,
    EncounterSet.LaidToRest,
    EncounterSet.ReadOrDie,
    EncounterSet.RedTideRising,
    EncounterSet.RelicsOfThePast,
  ],
  [Product.ThePathToCarcosaCampaignExpansion]: [
    EncounterSet.APhantomOfTruth,
    EncounterSet.BlackStarsRise,
    EncounterSet.Byakhee,
    EncounterSet.CultOfTheYellowSign,
    EncounterSet.CurtainCall,
    EncounterSet.DecayAndFilth,
    EncounterSet.Delusions,
    EncounterSet.DimCarcosa,
    EncounterSet.EchoesOfThePast,
    EncounterSet.EvilPortents,
    EncounterSet.TheFloodBelow,
    EncounterSet.HastursGift,
    EncounterSet.Hauntings,
    EncounterSet.InhabitantsOfCarcosa,
    EncounterSet.TheStranger,
    EncounterSet.TheLastKing,
    EncounterSet.ThePallidMask,
    EncounterSet.TheUnspeakableOath,
    EncounterSet.TheVortexAbove,
  ],
  [Product.TheCircleUndoneCampaignExpansion]: [
    EncounterSet.AgentsOfAzathoth,
    EncounterSet.AnettesCoven,
    EncounterSet.AtDeathsDoorstep,
    EncounterSet.BeforeTheBlackThrone,
    EncounterSet.CityOfSins,
    EncounterSet.DisappearanceAtTheTwilightEstate,
    EncounterSet.ForTheGreaterGood,
    EncounterSet.InTheClutchesOfChaos,
    EncounterSet.InexorableFate,
    EncounterSet.MusicOfTheDamned,
    EncounterSet.RealmOfDeath,
    EncounterSet.SecretsOfTheUniverse,
    EncounterSet.SilverTwilightLodge,
    EncounterSet.SpectralPredators,
    EncounterSet.TheSecretName,
    EncounterSet.TheWagesOfSin,
    EncounterSet.TheWatcher,
    EncounterSet.TheWitchingHour,
    EncounterSet.TrappedSpirits,
    EncounterSet.UnionAndDisillusion,
    EncounterSet.Witchcraft,
  ],
  [Product.TheDrownedCityCampaignExpansion]: [
    EncounterSet.AlienMachinery,
    EncounterSet.CosmicLegacy,
    EncounterSet.CourtOfTheAncients,
    EncounterSet.DeepOnes,
    EncounterSet.Domination,
    EncounterSet.Dreams,
    EncounterSet.ElderMist,
    EncounterSet.ObsidianCanyons,
    EncounterSet.OneLastJob,
    EncounterSet.Pilgrims,
    EncounterSet.Rlyeh,
    EncounterSet.SepulchreOfTheSleeper,
    EncounterSet.StarSpawn,
    EncounterSet.Stowaways,
    EncounterSet.Tasks,
    EncounterSet.TdcExpedition,
    EncounterSet.TdcFlood,
    EncounterSet.TheApiary,
    EncounterSet.TheDoomOfArkhamPart1,
    EncounterSet.TheDoomOfArkhamPart2,
    EncounterSet.TheDrownedQuarter,
    EncounterSet.TheGrandVault,
    EncounterSet.TheInescapable,
    EncounterSet.TheWesternWall,
    EncounterSet.UnderseaCreatures,
  ],
  [Product.TheDreamEatersCampaignExpansion]: [
    EncounterSet.AThousandShapesOfHorror,
    EncounterSet.AgentsOfAtlachNacha,
    EncounterSet.AgentsOfNyarlathotep,
    EncounterSet.BeyondTheGatesOfSleep,
    EncounterSet.Corsairs,
    EncounterSet.CreaturesOfTheUnderworld,
    EncounterSet.DarkSideOfTheMoon,
    EncounterSet.DescentIntoThePitch,
    EncounterSet.DreamersCurse,
    EncounterSet.Dreamlands,
    EncounterSet.MergingRealities,
    EncounterSet.PointOfNoReturn,
    EncounterSet.Spiders,
    EncounterSet.TerrorOfTheVale,
    EncounterSet.TheSearchForKadath,
    EncounterSet.WakingNightmare,
    EncounterSet.WeaverOfTheCosmos,
    EncounterSet.WhereTheGodsDwell,
    EncounterSet.WhispersOfHypnos,
    EncounterSet.Zoogs,
  ],
  [Product.TheForgottenAgeCampaignExpansion]: [
    EncounterSet.AgentsOfYig,
    EncounterSet.Expedition,
    EncounterSet.TheDoomOfEztli,
    EncounterSet.TemporalFlux,
    EncounterSet.GuardiansOfTime,
    EncounterSet.HeartOfTheElders,
    EncounterSet.Knyan,
    EncounterSet.PillarsOfJudgment,
    EncounterSet.PnakoticBrotherhood,
    EncounterSet.Poison,
    EncounterSet.Rainforest,
    EncounterSet.ForgottenRuins,
    EncounterSet.Serpents,
    EncounterSet.ShatteredAeons,
    EncounterSet.TheBoundaryBeyond,
    EncounterSet.TheCityOfArchives,
    EncounterSet.TheDepthsOfYoth,
    EncounterSet.ThreadsOfFate,
    EncounterSet.DeadlyTraps,
    EncounterSet.TurnBackTime,
    EncounterSet.YigsVenom,
    EncounterSet.TheUntamedWilds,
  ],
  [Product.TheInnsmouthConspiracyCampaignExpansion]: [
    EncounterSet.ALightInTheFog,
    EncounterSet.AgentsOfDagon,
    EncounterSet.AgentsOfHydra,
    EncounterSet.CreaturesOfTheDeep,
    EncounterSet.DevilReef,
    EncounterSet.FloodedCaverns,
    EncounterSet.FogOverInnsmouth,
    EncounterSet.HorrorInHighGear,
    EncounterSet.InTooDeep,
    EncounterSet.IntoTheMaelstrom,
    EncounterSet.Malfunction,
    EncounterSet.RisingTide,
    EncounterSet.ShatteredMemories,
    EncounterSet.Syzygy,
    EncounterSet.TheLairOfDagon,
    EncounterSet.TheLocals,
    EncounterSet.ThePitOfDespair,
    EncounterSet.TheVanishingOfElinaHarper,
  ],
  [Product.TheScarletKeysCampaignExpansion]: [
    EncounterSet.AgentsOfTheOutside,
    EncounterSet.AgentsOfYuggoth,
    EncounterSet.BeyondTheBeyond,
    EncounterSet.CleanupCrew,
    EncounterSet.CongressOfTheKeys,
    EncounterSet.CrimsonConspiracy,
    EncounterSet.DancingMad,
    EncounterSet.DarkVeiling,
    EncounterSet.DeadHeat,
    EncounterSet.DealingsInTheDark,
    EncounterSet.DogsOfWar,
    EncounterSet.Globetrotting,
    EncounterSet.MysteriesAbound,
    EncounterSet.OnThinIce,
    EncounterSet.Outsiders,
    EncounterSet.RedCoterie,
    EncounterSet.RiddlesAndRain,
    EncounterSet.SanguineShadows,
    EncounterSet.ScarletSorcery,
    EncounterSet.SecretWar,
    EncounterSet.ShadesOfSuffering,
    EncounterSet.ShadowOfADoubt,
    EncounterSet.SpatialAnomaly,
    EncounterSet.SpreadingCorruption,
    EncounterSet.StrangeHappenings,
    EncounterSet.WithoutATrace,
  ],
  [Product.ReturnToTheDunwichLegacy]: [
    EncounterSet.BeyondTheThreshold,
    EncounterSet.CreepingCold,
    EncounterSet.ErraticFear,
    EncounterSet.ResurgentEvils,
    EncounterSet.ReturnToBloodOnTheAltar,
    EncounterSet.ReturnToExtracurricularActivity,
    EncounterSet.ReturnToLostInTimeAndSpace,
    EncounterSet.ReturnToTheEssexCountyExpress,
    EncounterSet.ReturnToTheHouseAlwaysWins,
    EncounterSet.ReturnToTheMiskatonicMuseum,
    EncounterSet.ReturnToUndimensionedAndUnseen,
    EncounterSet.ReturnToWhereDoomAwaits,
    EncounterSet.SecretDoors,
    EncounterSet.YogSothothsEmissaries,
  ],
  [Product.ReturnToTheNightOfTheZealot]: [
    EncounterSet.GhoulsOfUmordhoth,
    EncounterSet.ReturnToCultOfUmordhoth,
    EncounterSet.ReturnToTheDevourerBelow,
    EncounterSet.ReturnToTheGathering,
    EncounterSet.ReturnToTheMidnightMasks,
    EncounterSet.TheDevourersCult,
  ],
  [Product.ReturnToThePathToCarcosa]: [
    EncounterSet.DecayingReality,
    EncounterSet.DelusoryEvils,
    EncounterSet.HastursEnvoys,
    EncounterSet.MaddeningDelusions,
    EncounterSet.NeuroticFear,
    EncounterSet.ReturnToAPhantomOfTruth,
    EncounterSet.ReturnToBlackStarsRise,
    EncounterSet.ReturnToCurtainCall,
    EncounterSet.ReturnToDimCarcosa,
    EncounterSet.ReturnToEchoesOfThePast,
    EncounterSet.ReturnToTheLastKing,
    EncounterSet.ReturnToThePallidMask,
    EncounterSet.ReturnToTheUnspeakableOath,
  ],
  [Product.ReturnToTheCircleUndone]: [
    EncounterSet.BloodthirstySpirits,
    EncounterSet.ChillingMists,
    EncounterSet.CityOfTheDamned,
    EncounterSet.Hexcraft,
    EncounterSet.ImpendingEvils,
    EncounterSet.ReturnToAtDeathsDoorstep,
    EncounterSet.ReturnToBeforeTheBlackThrone,
    EncounterSet.ReturnToDisappearanceAtTheTwilightEstate,
    EncounterSet.ReturnToForTheGreaterGood,
    EncounterSet.ReturnToInTheClutchesOfChaos,
    EncounterSet.ReturnToTheSecretName,
    EncounterSet.ReturnToTheWagesOfSin,
    EncounterSet.ReturnToTheWitchingHour,
    EncounterSet.ReturnToUnionAndDisillusion,
    EncounterSet.UnspeakableFate,
    EncounterSet.UnstableRealm,
  ],
  [Product.ReturnToTheForgottenAge]: [
    EncounterSet.CultOfPnakotus,
    EncounterSet.DoomedExpedition,
    EncounterSet.ReturnToKnyan,
    EncounterSet.ReturnToPillarsOfJudgment,
    EncounterSet.ReturnToShatteredAeons,
    EncounterSet.ReturnToTheBoundaryBeyond,
    EncounterSet.ReturnToTheCityOfArchives,
    EncounterSet.ReturnToTheDepthsOfYoth,
    EncounterSet.ReturnToTheDoomOfEztli,
    EncounterSet.ReturnToTheRainforest,
    EncounterSet.ReturnToTheUntamedWilds,
    EncounterSet.ReturnToThreadsOfFate,
    EncounterSet.ReturnToTurnBackTime,
    EncounterSet.TemporalHunters,
    EncounterSet.VenomousHate,
  ],
  [Product.CurseOfTheRougarou]: [EncounterSet.TheBayou, EncounterSet.CurseOfTheRougarou],
  [Product.CarnevaleOfHorrors]: [EncounterSet.CarnevaleOfHorrors],
  [Product.TheLabyrinthsOfLunacy]: [
    EncounterSet.TheLabyrinthsOfLunacyEpicMultiplayer,
    EncounterSet.TheLabyrinthsOfLunacy,
    EncounterSet.TheLabyrinthsOfLunacySingleGroup,
  ],
  [Product.GuardiansOfTheAbyss]: [
    EncounterSet.AbyssalGifts,
    EncounterSet.AbyssalTribute,
    EncounterSet.BrotherhoodOfTheBeast,
    EncounterSet.SandsOfEgypt,
    EncounterSet.TheEternalSlumber,
    EncounterSet.TheNightsUsurper,
  ],
  [Product.MurderAtTheExcelsiorHotel]: [
    EncounterSet.AlienInterference,
    EncounterSet.DarkRituals,
    EncounterSet.ExcelsiorManagement,
    EncounterSet.MurderAtTheExcelsiorHotel,
    EncounterSet.SinsOfThePast,
    EncounterSet.VileExperiments,
  ],
  [Product.TheBlobThatAteEverything]: [
    EncounterSet.TheBlobThatAteEverything,
    EncounterSet.TheBlobThatAteEverythingEpicMultiplayer,
    EncounterSet.TheBlobThatAteEverythingSingleGroup,
    EncounterSet.MigoIncursion,
  ],
  [Product.TheBlobThatAteEverythingElse]: [
    EncounterSet.TheBlobThatAteEverythingElse,
    EncounterSet.MigoIncursionII,
  ],
  [Product.WarOfTheOuterGods]: [
    EncounterSet.ChildrenOfParadise,
    EncounterSet.DeathOfStars,
    EncounterSet.SwarmOfAssimilation,
    EncounterSet.WarOfTheOuterGods,
  ],
  [Product.MachinationsThroughTime]: [
    EncounterSet.MachinationsThroughTime,
    EncounterSet.MachinationsThroughTimeEpicMultiplayer,
    EncounterSet.MachinationsThroughTimeSingleGroup,
  ],
  [Product.FortuneAndFolly]: [
    EncounterSet.FortuneAndFolly,
    EncounterSet.FortunesChosen,
    EncounterSet.PlanInShambles,
  ],
  [Product.TheMidwinterGala]: [EncounterSet.TheMidwinterGala],
  [Product.FilmFatale]: [
    EncounterSet.AbominableContessa,
    EncounterSet.CosmicJourney,
    EncounterSet.FilmFatale,
    EncounterSet.ForgottenIsland,
  ],
  [Product.CoreSet2026]: [],
};

/**
 * Maps Campaigns to their associated EncounterSets.
 * Combines encounter sets from both Campaign and Investigator expansion products.
 */
export const campaignEncounterSetsMap: Record<Campaign, EncounterSet[]> = {
  [Campaign.NightOfTheZealot]: productEncounterSetsMap[Product.CoreSet] || [],
  [Campaign.TheDunwichLegacy]:
    productEncounterSetsMap[Product.TheDunwichLegacyCampaignExpansion] || [],
  [Campaign.ThePathToCarcosa]:
    productEncounterSetsMap[Product.ThePathToCarcosaCampaignExpansion] || [],
  [Campaign.TheForgottenAge]:
    productEncounterSetsMap[Product.TheForgottenAgeCampaignExpansion] || [],
  [Campaign.TheCircleUndone]:
    productEncounterSetsMap[Product.TheCircleUndoneCampaignExpansion] || [],
  [Campaign.TheDreamQuest]: productEncounterSetsMap[Product.TheDreamEatersCampaignExpansion] || [],
  [Campaign.TheWebOfDreams]: productEncounterSetsMap[Product.TheDreamEatersCampaignExpansion] || [],
  [Campaign.TheInnsmouthConspiracy]:
    productEncounterSetsMap[Product.TheInnsmouthConspiracyCampaignExpansion] || [],
  [Campaign.EdgeOfTheEarth]: productEncounterSetsMap[Product.EdgeOfTheEarthCampaignExpansion] || [],
  [Campaign.TheScarletKeys]: productEncounterSetsMap[Product.TheScarletKeysCampaignExpansion] || [],
  [Campaign.TheFeastOfHemlockVale]:
    productEncounterSetsMap[Product.TheFeastOfHemlockValeCampaignExpansion] || [],
  [Campaign.TheDrownedCity]: productEncounterSetsMap[Product.TheDrownedCityCampaignExpansion] || [],
  [Campaign.ReturnToNightOfTheZealot]:
    productEncounterSetsMap[Product.ReturnToTheNightOfTheZealot] || [],
  [Campaign.ReturnToTheDunwichLegacy]:
    productEncounterSetsMap[Product.ReturnToTheDunwichLegacy] || [],
  [Campaign.ReturnToThePathToCarcosa]:
    productEncounterSetsMap[Product.ReturnToThePathToCarcosa] || [],
  [Campaign.ReturnToTheForgottenAge]: productEncounterSetsMap[Product.ReturnToTheForgottenAge] || [],
  [Campaign.ReturnToTheCircleUndone]: productEncounterSetsMap[Product.ReturnToTheCircleUndone] || [],
  [Campaign.BrethrenOfAsh]: productEncounterSetsMap[Product.CoreSet2026] || [],
};

/**
 * Maps StandaloneScenarios to their associated EncounterSets.
 */
export const standaloneEncounterSetsMap: Record<StandaloneScenario, EncounterSet[]> = {
  [StandaloneScenario.CurseOfTheRougarou]: productEncounterSetsMap[Product.CurseOfTheRougarou] || [],
  [StandaloneScenario.CarnevaleOfHorrors]: productEncounterSetsMap[Product.CarnevaleOfHorrors] || [],
  [StandaloneScenario.TheLabyrinthsOfLunacy]:
    productEncounterSetsMap[Product.TheLabyrinthsOfLunacy] || [],
  [StandaloneScenario.GuardiansOfTheAbyss]:
    productEncounterSetsMap[Product.GuardiansOfTheAbyss] || [],
  [StandaloneScenario.MurderAtTheExcelsiorHotel]:
    productEncounterSetsMap[Product.MurderAtTheExcelsiorHotel] || [],
  [StandaloneScenario.TheBlobThatAteEverything]:
    productEncounterSetsMap[Product.TheBlobThatAteEverything] || [],
  [StandaloneScenario.TheBlobThatAteEverythingElse]:
    productEncounterSetsMap[Product.TheBlobThatAteEverythingElse] || [],
  [StandaloneScenario.WarOfTheOuterGods]: productEncounterSetsMap[Product.WarOfTheOuterGods] || [],
  [StandaloneScenario.MachinationsThroughTime]:
    productEncounterSetsMap[Product.MachinationsThroughTime] || [],
  [StandaloneScenario.FortuneAndFolly]: productEncounterSetsMap[Product.FortuneAndFolly] || [],
  [StandaloneScenario.TheMidwinterGala]: productEncounterSetsMap[Product.TheMidwinterGala] || [],
  [StandaloneScenario.FilmFatale]: productEncounterSetsMap[Product.FilmFatale] || [],
};

/**
 * Separated so they do not get used in scenarioExclusiveEncounterSets,
 * these could be reused in other scenarios even though they were
 * one of the scenario's name.
 */
export const coreScenarioNameEncounterSets: readonly EncounterSet[] = [
  // Core Set
  EncounterSet.TheGathering,
  EncounterSet.TheMidnightMasks,
  EncounterSet.TheDevourerBelow,
]

/**
 * Encounter sets that are also scenario names.
 * Every scenario has an encounter set with the same name.
 */
export const noncoreScenarioNameEncounterSets: readonly EncounterSet[] = [
  // The Dunwich Legacy
  EncounterSet.ExtracurricularActivity,
  EncounterSet.TheHouseAlwaysWins,
  EncounterSet.TheMiskatonicMuseum,
  EncounterSet.TheEssexCountyExpress,
  EncounterSet.BloodOnTheAltar,
  EncounterSet.UndimensionedAndUnseen,
  EncounterSet.WhereDoomAwaits,
  EncounterSet.LostInTimeAndSpace,

  // The Path to Carcosa
  EncounterSet.CurtainCall,
  EncounterSet.TheLastKing,
  EncounterSet.EchoesOfThePast,
  EncounterSet.TheUnspeakableOath,
  EncounterSet.APhantomOfTruth,
  EncounterSet.ThePallidMask,
  EncounterSet.BlackStarsRise,
  EncounterSet.DimCarcosa,

  // The Forgotten Age
  EncounterSet.TheUntamedWilds,
  EncounterSet.TheDoomOfEztli,
  EncounterSet.ThreadsOfFate,
  EncounterSet.TheBoundaryBeyond,
  EncounterSet.HeartOfTheElders,
  EncounterSet.TheCityOfArchives,
  EncounterSet.TheDepthsOfYoth,
  EncounterSet.ShatteredAeons,
  EncounterSet.TurnBackTime,

  // The Circle Undone
  EncounterSet.DisappearanceAtTheTwilightEstate,
  EncounterSet.TheWitchingHour,
  EncounterSet.AtDeathsDoorstep,
  EncounterSet.TheSecretName,
  EncounterSet.TheWagesOfSin,
  EncounterSet.ForTheGreaterGood,
  EncounterSet.UnionAndDisillusion,
  EncounterSet.InTheClutchesOfChaos,
  EncounterSet.BeforeTheBlackThrone,

  // The Dream-Eaters
  EncounterSet.BeyondTheGatesOfSleep,
  EncounterSet.WakingNightmare,
  EncounterSet.TheSearchForKadath,
  EncounterSet.AThousandShapesOfHorror,
  EncounterSet.DarkSideOfTheMoon,
  EncounterSet.PointOfNoReturn,
  EncounterSet.WhereTheGodsDwell,
  EncounterSet.WeaverOfTheCosmos,

  // The Innsmouth Conspiracy
  EncounterSet.ThePitOfDespair,
  EncounterSet.TheVanishingOfElinaHarper,
  EncounterSet.InTooDeep,
  EncounterSet.DevilReef,
  EncounterSet.HorrorInHighGear,
  EncounterSet.ALightInTheFog,
  EncounterSet.TheLairOfDagon,
  EncounterSet.IntoTheMaelstrom,

  // Edge of the Earth
  EncounterSet.IceAndDeath,
  EncounterSet.FatalMirage,
  EncounterSet.ToTheForbiddenPeaks,
  EncounterSet.CityOfTheElderThings,
  EncounterSet.TheHeartOfMadness,

  // The Scarlet Keys
  EncounterSet.RiddlesAndRain,
  EncounterSet.DeadHeat,
  EncounterSet.SanguineShadows,
  EncounterSet.DealingsInTheDark,
  EncounterSet.DancingMad,
  EncounterSet.OnThinIce,
  EncounterSet.DogsOfWar,
  EncounterSet.ShadesOfSuffering,
  EncounterSet.WithoutATrace,
  EncounterSet.CongressOfTheKeys,

  // The Feast of Hemlock Vale
  EncounterSet.WrittenInRock,
  EncounterSet.HemlockHouse,
  EncounterSet.TheSilentHeath,
  EncounterSet.TheLostSister,
  EncounterSet.TheThingInTheDepths,
  EncounterSet.TheTwistedHollow,
  EncounterSet.TheLongestNight,
  EncounterSet.FateOfTheVale,

  // The Drowned City
  EncounterSet.OneLastJob,
  EncounterSet.TheDrownedQuarter,
  EncounterSet.TheWesternWall,
  EncounterSet.TheGrandVault,
  EncounterSet.TheApiary,
  EncounterSet.CourtOfTheAncients,
  EncounterSet.ObsidianCanyons,
  EncounterSet.SepulchreOfTheSleeper,
  EncounterSet.TheDoomOfArkhamPart1,
  EncounterSet.TheDoomOfArkhamPart2,

  // Return to Night of the Zealot
  EncounterSet.ReturnToTheGathering,
  EncounterSet.ReturnToTheMidnightMasks,
  EncounterSet.ReturnToTheDevourerBelow,

  // Return to The Dunwich Legacy
  EncounterSet.ReturnToExtracurricularActivity,
  EncounterSet.ReturnToTheHouseAlwaysWins,
  EncounterSet.ReturnToTheMiskatonicMuseum,
  EncounterSet.ReturnToTheEssexCountyExpress,
  EncounterSet.ReturnToBloodOnTheAltar,
  EncounterSet.ReturnToUndimensionedAndUnseen,
  EncounterSet.ReturnToWhereDoomAwaits,
  EncounterSet.ReturnToLostInTimeAndSpace,

  // Return to The Path to Carcosa
  EncounterSet.ReturnToCurtainCall,
  EncounterSet.ReturnToTheLastKing,
  EncounterSet.ReturnToEchoesOfThePast,
  EncounterSet.ReturnToTheUnspeakableOath,
  EncounterSet.ReturnToAPhantomOfTruth,
  EncounterSet.ReturnToThePallidMask,
  EncounterSet.ReturnToBlackStarsRise,
  EncounterSet.ReturnToDimCarcosa,

  // Return to The Forgotten Age
  EncounterSet.ReturnToTheUntamedWilds,
  EncounterSet.ReturnToTheDoomOfEztli,
  EncounterSet.ReturnToThreadsOfFate,
  EncounterSet.ReturnToTheBoundaryBeyond,
  EncounterSet.ReturnToTheCityOfArchives,
  EncounterSet.ReturnToTheDepthsOfYoth,
  EncounterSet.ReturnToShatteredAeons,
  EncounterSet.ReturnToTurnBackTime,
  EncounterSet.ReturnToPillarsOfJudgment,
  EncounterSet.ReturnToKnyan,

  // Return to The Circle Undone
  EncounterSet.ReturnToDisappearanceAtTheTwilightEstate,
  EncounterSet.ReturnToTheWitchingHour,
  EncounterSet.ReturnToAtDeathsDoorstep,
  EncounterSet.ReturnToTheSecretName,
  EncounterSet.ReturnToTheWagesOfSin,
  EncounterSet.ReturnToForTheGreaterGood,
  EncounterSet.ReturnToUnionAndDisillusion,
  EncounterSet.ReturnToInTheClutchesOfChaos,
  EncounterSet.ReturnToBeforeTheBlackThrone,

  // Standalone Scenarios
  EncounterSet.CurseOfTheRougarou,
  EncounterSet.CarnevaleOfHorrors,
  EncounterSet.TheLabyrinthsOfLunacy,
  EncounterSet.TheNightsUsurper,
  EncounterSet.TheEternalSlumber,
  EncounterSet.MurderAtTheExcelsiorHotel,
  EncounterSet.TheBlobThatAteEverything,
  EncounterSet.TheBlobThatAteEverythingElse,
  EncounterSet.WarOfTheOuterGods,
  EncounterSet.MachinationsThroughTime,
  EncounterSet.FortuneAndFolly,
  EncounterSet.TheMidwinterGala,
  EncounterSet.FilmFatale,

  // Parallel Scenarios
  EncounterSet.AllOrNothing,
  EncounterSet.ReadOrDie,
  EncounterSet.ByTheBook,
  EncounterSet.LaidToRest,
  EncounterSet.RedTideRising,
  EncounterSet.RelicsOfThePast,
] as const;

export const scenarioNameEncounterSets: readonly EncounterSet[] = [
  ...coreScenarioNameEncounterSets,
  ...noncoreScenarioNameEncounterSets,
] as const;

/**
 * Encounter sets that are exclusive to one scenario.
 * This includes scenario name encounter sets plus other scenario-specific sets.
 */
export const scenarioExclusiveEncounterSets: readonly EncounterSet[] = [
  ...noncoreScenarioNameEncounterSets,

  // The Path to Carcosa
  EncounterSet.TheFloodBelow,
  EncounterSet.TheVortexAbove,

  // The Forgotten Age
  EncounterSet.PillarsOfJudgment,
  EncounterSet.Knyan,

  // The Dream-Eaters
  EncounterSet.TerrorOfTheVale,
  EncounterSet.DescentIntoThePitch,

  // Edge of the Earth
  EncounterSet.TheCrash,
  EncounterSet.LostInTheNight,
  EncounterSet.SeepingNightmares,
  EncounterSet.MemorialsOfTheLost,
  EncounterSet.TheGreatSeal,
  EncounterSet.StirringInTheDeep,

  // The Feast of Hemlock Vale - Day encounter sets used in scenarios
  EncounterSet.TheFirstDay,
  EncounterSet.TheSecondDay,
  EncounterSet.DayOfRest,
  EncounterSet.DayOfRain,
  EncounterSet.DayOfTheFeast,
  EncounterSet.TheFinalDay,
] as const;

/**
 * If exist in this array, instead of ordered by name,
 * these encounter sets are ordered in this order, and comes
 * before all other encounter sets.
 */
export const specialOrderingEncounterSets: readonly EncounterSet[] = [
  EncounterSet.TheFirstDay,
  EncounterSet.DayOfRest,
  EncounterSet.TheSecondDay,
  EncounterSet.DayOfRain,
  EncounterSet.TheFinalDay,
  EncounterSet.DayOfTheFeast,
]



