<script lang="ts">
  import { EncounterSet } from "@5argon/arkham-kohaku";
  import type { ComponentType } from "svelte";

  interface Prop {
    encounterSet: EncounterSet;
  }
  const { encounterSet }: Prop = $props();

  function getIconComponent(set: EncounterSet) {
    switch (set) {
      case EncounterSet.AgentsOfCthulhu:
        return import("../individual/svelte/AgentsOfCthulhu.svelte");
      case EncounterSet.AgentsOfHastur:
        return import("../individual/svelte/AgentsOfHastur.svelte");
      case EncounterSet.AgentsOfShubniggurath:
        return import("../individual/svelte/AgentsOfShub.svelte");
      case EncounterSet.AgentsOfYogsothoth:
        return import("../individual/svelte/AgentsOfYog.svelte");
      case EncounterSet.AncientEvils:
        return import("../individual/svelte/AncientEvils.svelte");
      case EncounterSet.ChillingCold:
        return import("../individual/svelte/ChillingCold.svelte");
      case EncounterSet.CultOfUmrdhoth:
        return import("../individual/svelte/CultOfUmordoth.svelte");
      case EncounterSet.DarkCult:
        return import("../individual/svelte/DarkCult.svelte");
      case EncounterSet.Ghouls:
        return import("../individual/svelte/Ghouls.svelte");
      case EncounterSet.LockedDoors:
        return import("../individual/svelte/LockedDoors.svelte");
      case EncounterSet.Nightgaunts:
        return import("../individual/svelte/Nightgaunts.svelte");
      case EncounterSet.Rats:
        return import("../individual/svelte/Rats.svelte");
      case EncounterSet.StrikingFear:
        return import("../individual/svelte/StrikingFear.svelte");
      case EncounterSet.TheDevourerBelow:
        return import("../individual/svelte/TheDevourerBelow.svelte");
      case EncounterSet.TheGathering:
        return import("../individual/svelte/TheGathering.svelte");
      case EncounterSet.TheMidnightMasks:
        return import("../individual/svelte/MidnightMasks.svelte");
      case EncounterSet.ArmitagesFate:
        return import("../individual/svelte/ArmitagesFate.svelte");
      case EncounterSet.BadLuck:
        return import("../individual/svelte/BadLuck.svelte");
      case EncounterSet.BeastThralls:
        return import("../individual/svelte/BeastThralls.svelte");
      case EncounterSet.BishopsThralls:
        return import("../individual/svelte/BishopsThralls.svelte");
      case EncounterSet.BloodOnTheAltar:
        return import("../individual/svelte/BloodOnTheAltar.svelte");
      case EncounterSet.Dunwich:
        return import("../individual/svelte/Dunwich.svelte");
      case EncounterSet.TheEssexCountyExpress:
        return import("../individual/svelte/TheEssexCountyExpress.svelte");
      case EncounterSet.ExtracurricularActivity:
        return import("../individual/svelte/ExtracurricularActivity.svelte");
      case EncounterSet.HideousAbominations:
        return import("../individual/svelte/HideousAbominations.svelte");
      case EncounterSet.LostInTimeAndSpace:
        return import("../individual/svelte/LostInTimeAndSpace.svelte");
      case EncounterSet.NaomisCrew:
        return import("../individual/svelte/NaomisCrew.svelte");
      case EncounterSet.Sorcery:
        return import("../individual/svelte/Sorcery.svelte");
      case EncounterSet.TheBeyond:
        return import("../individual/svelte/TheBeyond.svelte");
      case EncounterSet.TheHouseAlwaysWins:
        return import("../individual/svelte/TheHouseAlwaysWins.svelte");
      case EncounterSet.TheMiskatonicMuseum:
        return import("../individual/svelte/TheMiskatonicMuseum.svelte");
      case EncounterSet.UndimensionedAndUnseen:
        return import("../individual/svelte/UndimensionedAndUnseen.svelte");
      case EncounterSet.WhereDoomAwaits:
        return import("../individual/svelte/WhereDoomAwaits.svelte");
      case EncounterSet.Whippoorwills:
        return import("../individual/svelte/Whippoorwills.svelte");
      case EncounterSet.AgentsOfTheUnknown:
        return import("../individual/svelte/AgentsOfTheUnknown.svelte");
      case EncounterSet.CityOfTheElderThings:
        return import("../individual/svelte/CityOfTheElderThings.svelte");
      case EncounterSet.CreaturesInTheIce:
        return import("../individual/svelte/CreaturesInTheIce.svelte");
      case EncounterSet.DeadlyWeather:
        return import("../individual/svelte/DeadlyWeather.svelte");
      case EncounterSet.ElderThings:
        return import("../individual/svelte/ElderThings.svelte");
      case EncounterSet.ExpeditionTeam:
        return import("../individual/svelte/ExpeditionTeam.svelte");
      case EncounterSet.FatalMirage:
        return import("../individual/svelte/FatalMirage.svelte");
      case EncounterSet.HazardsOfAntarctica:
        return import("../individual/svelte/HazardsOfAntarctica.svelte");
      case EncounterSet.IceAndDeath:
        return import("../individual/svelte/IceAndDeath.svelte");
      case EncounterSet.LeftBehind:
        return import("../individual/svelte/LeftBehind.svelte");
      case EncounterSet.LostInTheNight:
        return import("../individual/svelte/LostInTheNight.svelte");
      case EncounterSet.MemorialsOfTheLost:
        return import("../individual/svelte/MemorialsOfTheLost.svelte");
      case EncounterSet.Miasma:
        return import("../individual/svelte/Miasma.svelte");
      case EncounterSet.NamelessHorrors:
        return import("../individual/svelte/NamelessHorrors.svelte");
      case EncounterSet.Penguins:
        return import("../individual/svelte/Penguins.svelte");
      case EncounterSet.SeepingNightmares:
        return import("../individual/svelte/SleepingNightmares.svelte");
      case EncounterSet.Shoggoths:
        return import("../individual/svelte/Shoggoths.svelte");
      case EncounterSet.SilenceAndMystery:
        return import("../individual/svelte/SilenceAndMystery.svelte");
      case EncounterSet.StirringInTheDeep:
        return import("../individual/svelte/StirringInTheDeep.svelte");
      case EncounterSet.Tekelili:
        return import("../individual/svelte/TekeliLi.svelte");
      case EncounterSet.TheCrash:
        return import("../individual/svelte/TheCrash.svelte");
      case EncounterSet.TheGreatSeal:
        return import("../individual/svelte/TheGreatSeal.svelte");
      case EncounterSet.TheHeartOfMadness:
        return import("../individual/svelte/TheHeartOfMadness.svelte");
      case EncounterSet.ToTheForbiddenPeaks:
        return import("../individual/svelte/ToTheForbiddenPeaks.svelte");
      case EncounterSet.AgentsOfTheColour:
        return import("../individual/svelte/AgentsOfTheColour.svelte");
      case EncounterSet.Blight:
        return import("../individual/svelte/Blight.svelte");
      case EncounterSet.DayOfRain:
        return import("../individual/svelte/DayOfRain.svelte");
      case EncounterSet.DayOfRest:
        return import("../individual/svelte/DayOfRest.svelte");
      case EncounterSet.DayOfTheFeast:
        return import("../individual/svelte/DayOfTheFeast.svelte");
      case EncounterSet.FateOfTheVale:
        return import("../individual/svelte/FateOfTheVale.svelte");
      case EncounterSet.Fire:
        return import("../individual/svelte/Fire.svelte");
      case EncounterSet.Heirlooms:
        return import("../individual/svelte/Heirlooms.svelte");
      case EncounterSet.HemlockHouse:
        return import("../individual/svelte/HemlockHouse.svelte");
      case EncounterSet.HorrorsInTheRock:
        return import("../individual/svelte/HorrorsInTheRock.svelte");
      case EncounterSet.Mutations:
        return import("../individual/svelte/Mutations.svelte");
      case EncounterSet.Myconids:
        return import("../individual/svelte/Myconids.svelte");
      case EncounterSet.Refractions:
        return import("../individual/svelte/Refractions.svelte");
      case EncounterSet.Residents:
        return import("../individual/svelte/Residents.svelte");
      case EncounterSet.TheFinalDay:
        return import("../individual/svelte/TheFinalDay.svelte");
      case EncounterSet.TheFirstDay:
        return import("../individual/svelte/TheFirstDay.svelte");
      case EncounterSet.TheForest:
        return import("../individual/svelte/TheForest.svelte");
      case EncounterSet.TheLongestNight:
        return import("../individual/svelte/TheLongestNight.svelte");
      case EncounterSet.TheLostSister:
        return import("../individual/svelte/TheLostSister.svelte");
      case EncounterSet.TheSecondDay:
        return import("../individual/svelte/TheSecondDay.svelte");
      case EncounterSet.TheSilentHeath:
        return import("../individual/svelte/TheSilentHeath.svelte");
      case EncounterSet.TheThingInTheDepths:
        return import("../individual/svelte/TheThingInTheDepths.svelte");
      case EncounterSet.TheTwistedHollow:
        return import("../individual/svelte/TheTwistedHollow.svelte");
      case EncounterSet.TheVale:
        return import("../individual/svelte/TheVale.svelte");
      case EncounterSet.Transfiguration:
        return import("../individual/svelte/Transfiguration.svelte");
      case EncounterSet.WrittenInRock:
        return import("../individual/svelte/WrittenInRock.svelte");
      case EncounterSet.AllOrNothing:
        return import("../individual/svelte/AllOrNothing.svelte");
      case EncounterSet.BadBlood:
        return import("../individual/svelte/BadBlood.svelte");
      case EncounterSet.ByTheBook:
        return import("../individual/svelte/ByTheBook.svelte");
      case EncounterSet.LaidToRest:
        return import("../individual/svelte/LaidToRest.svelte");
      case EncounterSet.ReadOrDie:
        return import("../individual/svelte/ReadOrDie.svelte");
      case EncounterSet.RedTideRising:
        return import("../individual/svelte/RedTideRising.svelte");
      case EncounterSet.RelicsOfThePast:
        return import("../individual/svelte/Rop.svelte");
      case EncounterSet.APhantomOfTruth:
        return import("../individual/svelte/APhantomOfTruth.svelte");
      case EncounterSet.BlackStarsRise:
        return import("../individual/svelte/BlackStarsRise.svelte");
      case EncounterSet.Byakhee:
        return import("../individual/svelte/Byakhee.svelte");
      case EncounterSet.CultOfTheYellowSign:
        return import("../individual/svelte/CultOfTheYellowSign.svelte");
      case EncounterSet.CurtainCall:
        return import("../individual/svelte/CurtainCall.svelte");
      case EncounterSet.DecayAndFilth:
        return import("../individual/svelte/DecayAndFilth.svelte");
      case EncounterSet.Delusions:
        return import("../individual/svelte/Delusions.svelte");
      case EncounterSet.DimCarcosa:
        return import("../individual/svelte/DimCarcosa.svelte");
      case EncounterSet.EchoesOfThePast:
        return import("../individual/svelte/EchoesOfThePast.svelte");
      case EncounterSet.EvilPortents:
        return import("../individual/svelte/EvilPortents.svelte");
      case EncounterSet.TheFloodBelow:
        return import("../individual/svelte/TheFloodBelow.svelte");
      case EncounterSet.HastursGift:
        return import("../individual/svelte/HastursGift.svelte");
      case EncounterSet.Hauntings:
        return import("../individual/svelte/Hauntings.svelte");
      case EncounterSet.InhabitantsOfCarcosa:
        return import("../individual/svelte/InhabitantsOfCarcosa.svelte");
      case EncounterSet.TheStranger:
        return import("../individual/svelte/TheStranger.svelte");
      case EncounterSet.TheLastKing:
        return import("../individual/svelte/TheLastKing.svelte");
      case EncounterSet.ThePallidMask:
        return import("../individual/svelte/ThePallidMask.svelte");
      case EncounterSet.TheUnspeakableOath:
        return import("../individual/svelte/TheUnspeakableOath.svelte");
      case EncounterSet.TheVortexAbove:
        return import("../individual/svelte/TheVortexAbove.svelte");
      case EncounterSet.AgentsOfAzathoth:
        return import("../individual/svelte/AgentsOfAzathoth.svelte");
      case EncounterSet.AnettesCoven:
        return import("../individual/svelte/AnettesCoven.svelte");
      case EncounterSet.AtDeathsDoorstep:
        return import("../individual/svelte/AtDeathsDoorstep.svelte");
      case EncounterSet.BeforeTheBlackThrone:
        return import("../individual/svelte/BeforeTheBlackThrone.svelte");
      case EncounterSet.CityOfSins:
        return import("../individual/svelte/CityOfSins.svelte");
      case EncounterSet.DisappearanceAtTheTwilightEstate:
        return import("../individual/svelte/DisappearanceAtTheTwilightEstate.svelte");
      case EncounterSet.ForTheGreaterGood:
        return import("../individual/svelte/ForTheGreaterGood.svelte");
      case EncounterSet.InTheClutchesOfChaos:
        return import("../individual/svelte/InTheClutchesOfChaos.svelte");
      case EncounterSet.InexorableFate:
        return import("../individual/svelte/InexorableFate.svelte");
      case EncounterSet.MusicOfTheDamned:
        return import("../individual/svelte/MusicOfTheDamned.svelte");
      case EncounterSet.RealmOfDeath:
        return import("../individual/svelte/RealmOfDeath.svelte");
      case EncounterSet.SecretsOfTheUniverse:
        return import("../individual/svelte/SecretsOfTheUniverse.svelte");
      case EncounterSet.SilverTwilightLodge:
        return import("../individual/svelte/SilverTwilightLodge.svelte");
      case EncounterSet.SpectralPredators:
        return import("../individual/svelte/SpectralPredators.svelte");
      case EncounterSet.TheSecretName:
        return import("../individual/svelte/TheSecretName.svelte");
      case EncounterSet.TheWagesOfSin:
        return import("../individual/svelte/TheWagesOfSin.svelte");
      case EncounterSet.TheWatcher:
        return import("../individual/svelte/TheWatcher.svelte");
      case EncounterSet.TheWitchingHour:
        return import("../individual/svelte/TheWitchingHour.svelte");
      case EncounterSet.TrappedSpirits:
        return import("../individual/svelte/TrappedSpirits.svelte");
      case EncounterSet.UnionAndDisillusion:
        return import("../individual/svelte/UnionAndDisillusion.svelte");
      case EncounterSet.Witchcraft:
        return import("../individual/svelte/Witchcraft.svelte");
      case EncounterSet.AlienMachinery:
        return import("../individual/svelte/AlienMachinery.svelte");
      case EncounterSet.CosmicLegacy:
        return import("../individual/svelte/CosmicLegacy.svelte");
      case EncounterSet.CourtOfTheAncients:
        return import("../individual/svelte/CourtOfTheAncients.svelte");
      case EncounterSet.DeepOnes:
        return import("../individual/svelte/DeepOnes.svelte");
      case EncounterSet.Domination:
        return import("../individual/svelte/Domination.svelte");
      case EncounterSet.Dreams:
        return import("../individual/svelte/Dreams.svelte");
      case EncounterSet.ElderMist:
        return import("../individual/svelte/ElderMist.svelte");
      case EncounterSet.ObsidianCanyons:
        return import("../individual/svelte/ObsidianCanyons.svelte");
      case EncounterSet.OneLastJob:
        return import("../individual/svelte/OneLastJob.svelte");
      case EncounterSet.Pilgrims:
        return import("../individual/svelte/Pilgrims.svelte");
      case EncounterSet.Rlyeh:
        return import("../individual/svelte/Rlyeh.svelte");
      case EncounterSet.SepulchreOfTheSleeper:
        return import("../individual/svelte/SepulchreOfTheSleeper.svelte");
      case EncounterSet.StarSpawn:
        return import("../individual/svelte/StarSpawn.svelte");
      case EncounterSet.Stowaways:
        return import("../individual/svelte/Stowaways.svelte");
      case EncounterSet.Tasks:
        return import("../individual/svelte/Tasks.svelte");
      case EncounterSet.TdcExpedition:
        return import("../individual/svelte/TdcExpedition.svelte");
      case EncounterSet.TdcFlood:
        return import("../individual/svelte/TdcFlood.svelte");
      case EncounterSet.TheApiary:
        return import("../individual/svelte/TheApiary.svelte");
      case EncounterSet.TheDoomOfArkhamPart1:
        return import("../individual/svelte/TheDoomOfArkhamPart1.svelte");
      case EncounterSet.TheDoomOfArkhamPart2:
        return import("../individual/svelte/TheDoomOfArkhamPart2.svelte");
      case EncounterSet.TheDrownedQuarter:
        return import("../individual/svelte/TheDrownedQuarter.svelte");
      case EncounterSet.TheGrandVault:
        return import("../individual/svelte/TheGrandVault.svelte");
      case EncounterSet.TheInescapable:
        return import("../individual/svelte/TheInescapable.svelte");
      case EncounterSet.TheWesternWall:
        return import("../individual/svelte/TheWesternWall.svelte");
      case EncounterSet.UnderseaCreatures:
        return import("../individual/svelte/UnderseaCreatures.svelte");
      case EncounterSet.AgentsOfAtlachNacha:
        return import("../individual/svelte/AgentsOfAtlachNacha.svelte");
      case EncounterSet.AgentsOfNyarlathotep:
        return import("../individual/svelte/AgentsOfNyarlathotep.svelte");
      case EncounterSet.AThousandShapesOfHorror:
        return import("../individual/svelte/AThousandShapesOfHorror.svelte");
      case EncounterSet.BeyondTheGatesOfSleep:
        return import("../individual/svelte/BeyondTheGatesOfSleep.svelte");
      case EncounterSet.Corsairs:
        return import("../individual/svelte/Corsairs.svelte");
      case EncounterSet.CreaturesOfTheUnderworld:
        return import("../individual/svelte/CreaturesOfTheUnderworld.svelte");
      case EncounterSet.DarkSideOfTheMoon:
        return import("../individual/svelte/DarkSideOfTheMoon.svelte");
      case EncounterSet.DescentIntoThePitch:
        return import("../individual/svelte/DescentIntoThePitch.svelte");
      case EncounterSet.DreamersCurse:
        return import("../individual/svelte/DreamersCurse.svelte");
      case EncounterSet.Dreamlands:
        return import("../individual/svelte/Dreamlands.svelte");
      case EncounterSet.MergingRealities:
        return import("../individual/svelte/MergingRealities.svelte");
      case EncounterSet.PointOfNoReturn:
        return import("../individual/svelte/PointOfNoReturn.svelte");
      case EncounterSet.Spiders:
        return import("../individual/svelte/Spiders.svelte");
      case EncounterSet.TerrorOfTheVale:
        return import("../individual/svelte/TerrorOfTheVale.svelte");
      case EncounterSet.TheSearchForKadath:
        return import("../individual/svelte/TheSearchForKadath.svelte");
      case EncounterSet.WakingNightmare:
        return import("../individual/svelte/WakingNightmare.svelte");
      case EncounterSet.WeaverOfTheCosmos:
        return import("../individual/svelte/WeaverOfTheCosmos.svelte");
      case EncounterSet.WhereTheGodsDwell:
        return import("../individual/svelte/WhereGodsDwell.svelte");
      case EncounterSet.WhispersOfHypnos:
        return import("../individual/svelte/WhispersOfHypnos.svelte");
      case EncounterSet.Zoogs:
        return import("../individual/svelte/Zoogs.svelte");
      case EncounterSet.AgentsOfYig:
        return import("../individual/svelte/AgentsOfYig.svelte");
      case EncounterSet.Expedition:
        return import("../individual/svelte/Expedition.svelte");
      case EncounterSet.TheDoomOfEztli:
        return import("../individual/svelte/TheDoomOfEztli.svelte");
      case EncounterSet.TemporalFlux:
        return import("../individual/svelte/TemporalFlux.svelte");
      case EncounterSet.GuardiansOfTime:
        return import("../individual/svelte/GuardiansOfTime.svelte");
      case EncounterSet.HeartOfTheElders:
        return import("../individual/svelte/HeartOfTheElders.svelte");
      case EncounterSet.Knyan:
        return import("../individual/svelte/Knyan.svelte");
      case EncounterSet.PillarsOfJudgment:
        return import("../individual/svelte/PillarsOfJudgement.svelte");
      case EncounterSet.PnakoticBrotherhood:
        return import("../individual/svelte/PnakoticBrotherhood.svelte");
      case EncounterSet.Poison:
        return import("../individual/svelte/Poison.svelte");
      case EncounterSet.Rainforest:
        return import("../individual/svelte/Rainforest.svelte");
      case EncounterSet.ForgottenRuins:
        return import("../individual/svelte/ForgottenRuins.svelte");
      case EncounterSet.Serpents:
        return import("../individual/svelte/Serpents.svelte");
      case EncounterSet.ShatteredAeons:
        return import("../individual/svelte/ShatteredAeons.svelte");
      case EncounterSet.TheBoundaryBeyond:
        return import("../individual/svelte/TheBoundaryBeyond.svelte");
      case EncounterSet.TheCityOfArchives:
        return import("../individual/svelte/CityOfArchives.svelte");
      case EncounterSet.TheDepthsOfYoth:
        return import("../individual/svelte/TheDepthsOfYoth.svelte");
      case EncounterSet.ThreadsOfFate:
        return import("../individual/svelte/ThreadsOfFate.svelte");
      case EncounterSet.DeadlyTraps:
        return import("../individual/svelte/DeadlyTraps.svelte");
      case EncounterSet.TurnBackTime:
        return import("../individual/svelte/TurnBackTime.svelte");
      case EncounterSet.YigsVenom:
        return import("../individual/svelte/YigsVenom.svelte");
      case EncounterSet.TheUntamedWilds:
        return import("../individual/svelte/TheUntamedWilds.svelte");
      case EncounterSet.ALightInTheFog:
        return import("../individual/svelte/ALightInTheFog.svelte");
      case EncounterSet.AgentsOfDagon:
        return import("../individual/svelte/AgentsOfDagon.svelte");
      case EncounterSet.AgentsOfHydra:
        return import("../individual/svelte/AgentsOfHydra.svelte");
      case EncounterSet.CreaturesOfTheDeep:
        return import("../individual/svelte/CreaturesFromBelow.svelte");
      case EncounterSet.DevilReef:
        return import("../individual/svelte/DevilReef.svelte");
      case EncounterSet.FloodedCaverns:
        return import("../individual/svelte/FloodedCaves.svelte");
      case EncounterSet.FogOverInnsmouth:
        return import("../individual/svelte/FogOverInnsmouth.svelte");
      case EncounterSet.HorrorInHighGear:
        return import("../individual/svelte/HorrorInHighGear.svelte");
      case EncounterSet.InTooDeep:
        return import("../individual/svelte/InTooDeep.svelte");
      case EncounterSet.IntoTheMaelstrom:
        return import("../individual/svelte/IntoTheMaelstrom.svelte");
      case EncounterSet.Malfunction:
        return import("../individual/svelte/Malfunction.svelte");
      case EncounterSet.RisingTide:
        return import("../individual/svelte/RisingTide.svelte");
      case EncounterSet.ShatteredMemories:
        return import("../individual/svelte/ShatteredMemories.svelte");
      case EncounterSet.Syzygy:
        return import("../individual/svelte/Syzygy.svelte");
      case EncounterSet.TheLairOfDagon:
        return import("../individual/svelte/LairOfDagon.svelte");
      case EncounterSet.TheLocals:
        return import("../individual/svelte/Locals.svelte");
      case EncounterSet.ThePitOfDespair:
        return import("../individual/svelte/GrottoOfDespair.svelte");
      case EncounterSet.TheVanishingOfElinaHarper:
        return import("../individual/svelte/DisappearanceOfElinaHarper.svelte");
      case EncounterSet.AgentsOfTheOutside:
        return import("../individual/svelte/AgentsOfTheOutside.svelte");
      case EncounterSet.AgentsOfYuggoth:
        return import("../individual/svelte/AgentsOfYuggoth.svelte");
      case EncounterSet.BeyondTheBeyond:
        return import("../individual/svelte/BeyondTheBeyond.svelte");
      case EncounterSet.CleanupCrew:
        return import("../individual/svelte/CleanupCrew.svelte");
      case EncounterSet.CongressOfTheKeys:
        return import("../individual/svelte/CongressOfTheKeys.svelte");
      case EncounterSet.CrimsonConspiracy:
        return import("../individual/svelte/CrimsonConspiracy.svelte");
      case EncounterSet.DancingMad:
        return import("../individual/svelte/DancingMad.svelte");
      case EncounterSet.DarkVeiling:
        return import("../individual/svelte/DarkVeiling.svelte");
      case EncounterSet.DeadHeat:
        return import("../individual/svelte/DeadHeat.svelte");
      case EncounterSet.DealingsInTheDark:
        return import("../individual/svelte/DealingsInTheDark.svelte");
      case EncounterSet.DogsOfWar:
        return import("../individual/svelte/DogsOfWar.svelte");
      case EncounterSet.Globetrotting:
        return import("../individual/svelte/Globetrotting.svelte");
      case EncounterSet.MysteriesAbound:
        return import("../individual/svelte/MysteriesAbound.svelte");
      case EncounterSet.OnThinIce:
        return import("../individual/svelte/OnThinIce.svelte");
      case EncounterSet.Outsiders:
        return import("../individual/svelte/Outsiders.svelte");
      case EncounterSet.RedCoterie:
        return import("../individual/svelte/RedCoterie.svelte");
      case EncounterSet.RiddlesAndRain:
        return import("../individual/svelte/RiddlesAndRain.svelte");
      case EncounterSet.SanguineShadows:
        return import("../individual/svelte/SanguineShadows.svelte");
      case EncounterSet.ScarletSorcery:
        return import("../individual/svelte/ScarletSorcery.svelte");
      case EncounterSet.SecretWar:
        return import("../individual/svelte/SecretWar.svelte");
      case EncounterSet.ShadesOfSuffering:
        return import("../individual/svelte/ShadesOfSorrow.svelte");
      case EncounterSet.ShadowOfADoubt:
        return import("../individual/svelte/ShadowOfADoubt.svelte");
      case EncounterSet.SpatialAnomaly:
        return import("../individual/svelte/SpatialAnomaly.svelte");
      case EncounterSet.SpreadingCorruption:
        return import("../individual/svelte/SpreadingCorruption.svelte");
      case EncounterSet.StrangeHappenings:
        return import("../individual/svelte/StrangeHappenings.svelte");
      case EncounterSet.WithoutATrace:
        return import("../individual/svelte/WithoutATrace.svelte");
      case EncounterSet.BeyondTheThreshold:
        return import("../individual/svelte/BeyondTheThreshold.svelte");
      case EncounterSet.CreepingCold:
        return import("../individual/svelte/CreepingCold.svelte");
      case EncounterSet.ErraticFear:
        return import("../individual/svelte/ErraticFear.svelte");
      case EncounterSet.ResurgentEvils:
        return import("../individual/svelte/ResurgentEvils.svelte");
      case EncounterSet.ReturnToBloodOnTheAltar:
        return import("../individual/svelte/ReturnToBloodOnTheAltar.svelte");
      case EncounterSet.ReturnToExtracurricularActivity:
        return import("../individual/svelte/ReturnToExtracurricularActivities.svelte");
      case EncounterSet.ReturnToLostInTimeAndSpace:
        return import("../individual/svelte/ReturnToLostInTimeAndSpace.svelte");
      case EncounterSet.ReturnToTheEssexCountyExpress:
        return import("../individual/svelte/ReturnToTheEssexCountyExpress.svelte");
      case EncounterSet.ReturnToTheHouseAlwaysWins:
        return import("../individual/svelte/ReturnToTheHouseAlwaysWins.svelte");
      case EncounterSet.ReturnToTheMiskatonicMuseum:
        return import("../individual/svelte/ReturnToTheMiskatonicMuseum.svelte");
      case EncounterSet.ReturnToUndimensionedAndUnseen:
        return import("../individual/svelte/ReturnToUndimensionedAndUnseen.svelte");
      case EncounterSet.ReturnToWhereDoomAwaits:
        return import("../individual/svelte/ReturnToWhereDoomAwaits.svelte");
      case EncounterSet.SecretDoors:
        return import("../individual/svelte/SecretDoors.svelte");
      case EncounterSet.YogSothothsEmissaries:
        return import("../individual/svelte/YogSothothsEmissaries.svelte");
      case EncounterSet.GhoulsOfUmordhoth:
        return import("../individual/svelte/GhoulsOfUmrdhoth.svelte");
      case EncounterSet.ReturnToCultOfUmordhoth:
        return import("../individual/svelte/ReturnCult.svelte");
      case EncounterSet.ReturnToTheDevourerBelow:
        return import("../individual/svelte/ReturnToTheDevourerBelow.svelte");
      case EncounterSet.ReturnToTheGathering:
        return import("../individual/svelte/ReturnToTheGathering.svelte");
      case EncounterSet.ReturnToTheMidnightMasks:
        return import("../individual/svelte/ReturnToTheMidnightMasks.svelte");
      case EncounterSet.TheDevourersCult:
        return import("../individual/svelte/TheDevourersCult.svelte");
      case EncounterSet.DecayingReality:
        return import("../individual/svelte/DecayingReality.svelte");
      case EncounterSet.DelusoryEvils:
        return import("../individual/svelte/DelusoryEvils.svelte");
      case EncounterSet.HastursEnvoys:
        return import("../individual/svelte/HastursEnvoys.svelte");
      case EncounterSet.MaddeningDelusions:
        return import("../individual/svelte/MaddeningDelusions.svelte");
      case EncounterSet.NeuroticFear:
        return import("../individual/svelte/NeuroticFear.svelte");
      case EncounterSet.ReturnToAPhantomOfTruth:
        return import("../individual/svelte/ReturnToThePhantomOfTruth.svelte");
      case EncounterSet.ReturnToBlackStarsRise:
        return import("../individual/svelte/ReturnToBlackStarsRise.svelte");
      case EncounterSet.ReturnToCurtainCall:
        return import("../individual/svelte/ReturnToCurtainCall.svelte");
      case EncounterSet.ReturnToDimCarcosa:
        return import("../individual/svelte/ReturnToDimCarcosa.svelte");
      case EncounterSet.ReturnToEchoesOfThePast:
        return import("../individual/svelte/ReturnToEchoesOfThePast.svelte");
      case EncounterSet.ReturnToTheLastKing:
        return import("../individual/svelte/ReturnToTheLastKing.svelte");
      case EncounterSet.ReturnToThePallidMask:
        return import("../individual/svelte/ReturnToThePallidMask.svelte");
      case EncounterSet.ReturnToTheUnspeakableOath:
        return import("../individual/svelte/ReturnToTheUnspeakableOath.svelte");
      case EncounterSet.BloodthirstySpirits:
        return import("../individual/svelte/BloodthirstySpirits.svelte");
      case EncounterSet.ChillingMists:
        return import("../individual/svelte/ColdFog.svelte");
      case EncounterSet.CityOfTheDamned:
        return import("../individual/svelte/CityOfTheDamned.svelte");
      case EncounterSet.Hexcraft:
        return import("../individual/svelte/Witchwork.svelte");
      case EncounterSet.ImpendingEvils:
        return import("../individual/svelte/ThreateningEvil.svelte");
      case EncounterSet.ReturnToAtDeathsDoorstep:
        return import("../individual/svelte/ReturnToAtDeathsDoorstep.svelte");
      case EncounterSet.ReturnToBeforeTheBlackThrone:
        return import("../individual/svelte/ReturnToBeforeTheBlackThrone.svelte");
      case EncounterSet.ReturnToDisappearanceAtTheTwilightEstate:
        return import("../individual/svelte/ReturnToDisappearanceAtTheTwilightEstate.svelte");
      case EncounterSet.ReturnToForTheGreaterGood:
        return import("../individual/svelte/ReturnToForTheGreaterGood.svelte");
      case EncounterSet.ReturnToInTheClutchesOfChaos:
        return import("../individual/svelte/ReturnToInTheClutchesOfChaos.svelte");
      case EncounterSet.ReturnToTheSecretName:
        return import("../individual/svelte/ReturnToTheSecretName.svelte");
      case EncounterSet.ReturnToTheWagesOfSin:
        return import("../individual/svelte/ReturnToTheWagesOfSin.svelte");
      case EncounterSet.ReturnToTheWitchingHour:
        return import("../individual/svelte/ReturnToTheWitchingHour.svelte");
      case EncounterSet.ReturnToUnionAndDisillusion:
        return import("../individual/svelte/ReturnToUnionAndDisillusion.svelte");
      case EncounterSet.UnspeakableFate:
        return import("../individual/svelte/UnspeakableFate.svelte");
      case EncounterSet.UnstableRealm:
        return import("../individual/svelte/SpectralRealm.svelte");
      case EncounterSet.CultOfPnakotus:
        return import("../individual/svelte/CultOfPnakotus.svelte");
      case EncounterSet.DoomedExpedition:
        return import("../individual/svelte/DoomedExpedition.svelte");
      case EncounterSet.ReturnToKnyan:
        return import("../individual/svelte/ReturnToKnyan.svelte");
      case EncounterSet.ReturnToPillarsOfJudgment:
        return import("../individual/svelte/ReturnToPillarsOfJudgement.svelte");
      case EncounterSet.ReturnToShatteredAeons:
        return import("../individual/svelte/ReturnToShatteredAeons.svelte");
      case EncounterSet.ReturnToTheBoundaryBeyond:
        return import("../individual/svelte/ReturnToTheBoundaryBeyond.svelte");
      case EncounterSet.ReturnToTheCityOfArchives:
        return import("../individual/svelte/ReturnToCityOfArchives.svelte");
      case EncounterSet.ReturnToTheDepthsOfYoth:
        return import("../individual/svelte/ReturnToTheDepthsOfYoth.svelte");
      case EncounterSet.ReturnToTheDoomOfEztli:
        return import("../individual/svelte/ReturnToTheDoomOfEztli.svelte");
      case EncounterSet.ReturnToTheRainforest:
        return import("../individual/svelte/ReturnToTheRainforest.svelte");
      case EncounterSet.ReturnToTheUntamedWilds:
        return import("../individual/svelte/ReturnToTheUntamedWilds.svelte");
      case EncounterSet.ReturnToThreadsOfFate:
        return import("../individual/svelte/ReturnToThreadsOfFate.svelte");
      case EncounterSet.ReturnToTurnBackTime:
        return import("../individual/svelte/ReturnToTurnBackTime.svelte");
      case EncounterSet.TemporalHunters:
        return import("../individual/svelte/TemporalHunters.svelte");
      case EncounterSet.VenomousHate:
        return import("../individual/svelte/VenomousHate.svelte");
      case EncounterSet.TheBlobThatAteEverythingElse:
        return import("../individual/svelte/BlobThatAteEverythingElse.svelte");
      case EncounterSet.MigoIncursionII:
        return import("../individual/svelte/MigoIncursion2.svelte");
      case EncounterSet.TheBlobThatAteEverything:
        return import("../individual/svelte/TheBlobThatAteEverything.svelte");
      case EncounterSet.TheBlobThatAteEverythingEpicMultiplayer:
        return import("../individual/svelte/EpicMultiplayer.svelte");
      case EncounterSet.TheBlobThatAteEverythingSingleGroup:
        return import("../individual/svelte/SingleGroup.svelte");
      case EncounterSet.MigoIncursion:
        return import("../individual/svelte/Migo.svelte");
      case EncounterSet.CarnevaleOfHorrors:
        return import("../individual/svelte/Carnevale.svelte");
      case EncounterSet.TheBayou:
        return import("../individual/svelte/TheBayou.svelte");
      case EncounterSet.CurseOfTheRougarou:
        return import("../individual/svelte/CurseOfTheRougarou.svelte");
      case EncounterSet.AbominableContessa:
        return import("../individual/svelte/AbominableContessa.svelte");
      case EncounterSet.CosmicJourney:
        return import("../individual/svelte/CosmicJourney.svelte");
      case EncounterSet.FilmFatale:
        return import("../individual/svelte/FilmFatale.svelte");
      case EncounterSet.ForgottenIsland:
        return import("../individual/svelte/ForgottenIsland.svelte");
      case EncounterSet.FortuneAndFolly:
        return import("../individual/svelte/FortuneAndFolly.svelte");
      case EncounterSet.FortunesChosen:
        return import("../individual/svelte/FortunesChosen.svelte");
      case EncounterSet.PlanInShambles:
        return import("../individual/svelte/PlanInShambles.svelte");
      case EncounterSet.AbyssalGifts:
        return import("../individual/svelte/AbyssalGifts.svelte");
      case EncounterSet.AbyssalTribute:
        return import("../individual/svelte/AbyssalTribute.svelte");
      case EncounterSet.BrotherhoodOfTheBeast:
        return import("../individual/svelte/BrotherhoodOfTheBeast.svelte");
      case EncounterSet.SandsOfEgypt:
        return import("../individual/svelte/SandsOfEgypt.svelte");
      case EncounterSet.TheEternalSlumber:
        return import("../individual/svelte/EternalSlumber.svelte");
      case EncounterSet.TheNightsUsurper:
        return import("../individual/svelte/NightsUsurper.svelte");
      case EncounterSet.AlienInterference:
        return import("../individual/svelte/AlienInterference.svelte");
      case EncounterSet.DarkRituals:
        return import("../individual/svelte/DarkRituals.svelte");
      case EncounterSet.ExcelsiorManagement:
        return import("../individual/svelte/ExcelsiorManagement.svelte");
      case EncounterSet.MurderAtTheExcelsiorHotel:
        return import("../individual/svelte/MurderAtTheExcelsiorHotel.svelte");
      case EncounterSet.SinsOfThePast:
        return import("../individual/svelte/SinsOfThePast.svelte");
      case EncounterSet.VileExperiments:
        return import("../individual/svelte/VileExperiments.svelte");
      case EncounterSet.TheLabyrinthsOfLunacyEpicMultiplayer:
        return import("../individual/svelte/EpicMultiplayer.svelte");
      case EncounterSet.TheLabyrinthsOfLunacy:
        return import("../individual/svelte/InTheLabyrinthsOfLunacy.svelte");
      case EncounterSet.TheLabyrinthsOfLunacySingleGroup:
        return import("../individual/svelte/SingleGroup.svelte");
      case EncounterSet.MachinationsThroughTime:
        return import("../individual/svelte/MachinationsThroughTime.svelte");
      case EncounterSet.MachinationsThroughTimeEpicMultiplayer:
        return import("../individual/svelte/EpicMultiplayer.svelte");
      case EncounterSet.MachinationsThroughTimeSingleGroup:
        return import("../individual/svelte/SingleGroup.svelte");
      case EncounterSet.TheMidwinterGala:
        return import("../individual/svelte/Gala.svelte");
      case EncounterSet.ChildrenOfParadise:
        return import("../individual/svelte/ChildrenOfParadise.svelte");
      case EncounterSet.DeathOfStars:
        return import("../individual/svelte/DeathOfTheStars.svelte");
      case EncounterSet.SwarmOfAssimilation:
        return import("../individual/svelte/AssimilatingSwarm.svelte");
      case EncounterSet.WarOfTheOuterGods:
        return import("../individual/svelte/WarOfTheOuterGods.svelte");
      default:
        const _exhaustive: never = set;
        throw new Error(`Unhandled encounter set: ${_exhaustive}`);
    }
  }

  const iconComponent = $derived(getIconComponent(encounterSet));
</script>

{#await iconComponent}
  <!-- Optional: Loading state -->
  <span class="icon-loading" aria-label="Loading icon">...</span>
{:then module}
  {@const Icon = module.default}
  <Icon />
{:catch error}
  <!-- Error fallback -->
  <span class="icon-error" aria-label="Icon failed to load">⚠</span>
{/await}
