<!-- Generated by IcoMoon.io -->
<svg class="icon" version="1.1" xmlns="http://www.w3.org/2000/svg" width="30" height="32" viewBox="0 0 30 32">
<path d="M28.998 18.002l-15.584 10.487 2.759-7.062-15.171 4.014 3.885-7.439-3.885-7.48 15.171 4.014-2.759-7.025z"></path>
</svg>

<style>
  .icon {
    display: inline-block;
    width: 0.9375em;
    height: 1em;
    stroke-width: 0;
    stroke: currentColor;
    fill: currentColor;
  }
</style>
  