<!-- Generated by IcoMoon.io -->
<svg class="icon" version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
<path d="M12.735 29.468c-2.898-0.793-4.503-1.638-6.945-3.655-1.646-1.36-3.87-4.065-3.769-4.585 0.060-0.308 11.807-18.215 12.463-18.998 0.032-0.038 0.449 0.048 0.926 0.191 0.724 0.217 0.982 0.203 1.551-0.081l0.683-0.341 12.632 18.941-0.568 0.858c-0.792 1.197-3.464 3.972-4.662 4.841-2.079 1.509-3.778 2.263-6.888 3.058-1.794 0.459-3.111 0.403-5.424-0.23z"></path>
</svg>

<style>
  .icon {
    display: inline-block;
    width: 1.0087890625em;
    height: 1em;
    stroke-width: 0;
    stroke: currentColor;
    fill: currentColor;
  }
</style>
  