<!-- Generated by IcoMoon.io -->
<svg class="icon" version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
<path d="M6.842 12.211l-3.789 3.789 3.789 3.789v5.368h5.368l3.789 3.789 3.789-3.789h5.368v-5.368l3.789-3.789-3.789-3.79v-5.368h-5.368l-3.789-3.789-3.789 3.789h-5.368z"></path>
</svg>

<style>
  .icon {
    display: inline-block;
    width: 1em;
    height: 1em;
    stroke-width: 0;
    stroke: currentColor;
    fill: currentColor;
  }
</style>
  